### ISSUE TITLE
Is JQF based on portability？

### ISSUE THREAD

**Issue by zheng-yan-max** [rohanpadhye/JQF#101]
Hello author, I wonder if I have a program written in C.
Can I find his corner test cases through JQF? 
Or I can only find corner test cases for programs written in Java code。

**Comment by rohanpadhye** [comment]
Hi,

JQF can be used to fuzz-test any application that can be run in a JVM. This includes programs written in Java, Scala, Kotlin, and any other language for which there is a compiler to Java bytecode.

If you want to find bugs a program written in C, there are a lot of great fuzzing tools out there, such as [AFL](https://lcamtuf.coredump.cx/afl/) and [libFuzzer](https://github.com/google/fuzzing/blob/master/tutorial/libFuzzerTutorial.md).

Hope this helps.
