### ISSUE TITLE
Some problems on the run

### ISSUE THREAD

**Issue by zheng-yan-max** [rohanpadhye/JQF#103]
Dear author, I am very interested in the JQF that you have built, but I have been suffering from a lack of working right now. I've used JQF as a dependency for my Maven framer in your tutorial, but running the Zest test still shows that I have no JQF dependencies. How can I fix this? It would be nice if you had a specific picture or video of you running the ZEST test, and I hope to get an answer from you. Thank you very much.

`[ERROR] No plugin found for prefix 'jqf' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/zhengyan/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]`

**Comment by rohanpadhye** [comment]
Hello. I don't have a video but there are several [tutorials](https://github.com/rohanpadhye/JQF#tutorials) that walk you through the required steps. In particular, the [compiler fuzzing](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-a-Compiler) tutorial has a full example that shows dependencies to run the Maven plugin. Also check out the documentation of the [Maven plugin](https://github.com/rohanpadhye/jqf/wiki/JQF-Maven-Plugin) for the list of available options once you want to run the command.

You can also check out the [jqf-zest-example](https://github.com/rohanpadhye/jqf-zest-example) GitHub repo which is a fully working standalone test project that has all the necessary dependencies, etc. You can use that as a starting point.

Hope this helps.

**Comment by Xwen2** [comment]
> Dear author, I am very interested in the JQF that you have built, but I have been suffering from a lack of working right now. I've used JQF as a dependency for my Maven framer in your tutorial, but running the Zest test still shows that I have no JQF dependencies. How can I fix this? It would be nice if you had a specific picture or video of you running the ZEST test, and I hope to get an answer from you. Thank you very much.
> 
> `[ERROR] No plugin found for prefix 'jqf' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/zhengyan/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]`

@ddy-ddy Did you have a solution to this problem? I also encountered this issue. Could you share how you solved this problem?Thank you very much.
