### ISSUE TITLE
use the data

### ISSUE THREAD

**Issue by zheng-yan-max** [rohanpadhye/JQF#104]
Hi, author, if I wanted to use the results from the ZEST tests (successful and failed), how would I open the files corpus/ ID_000000 and Failures/ID_000000 and extract the contents?

**Comment by rohanpadhye** [comment]
Hello.

Assuming that you have run a test with a generator, the files themselves do not contain any human-readable data. The files contain binary data that helps you run your generators. You can run [`mvn jqf:repro`](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#reproducing-tests) to reproduce the test executions corresponding to the generator choices saved in those files. Be sure to read the [documentation of various options](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#flags-only-supported-by-jqfrepro) that repro supports.

**Comment by rohanpadhye** [comment]
See also #88.

**Comment by zheng-yan-max** [comment]
> Hello.
> 
> Assuming that you have run a test with a generator, the files themselves do not contain any human-readable data. The files contain binary data that helps you run your generators. You can run [`mvn jqf:repro`](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#reproducing-tests) to reproduce the test executions corresponding to the generator choices saved in those files. Be sure to read the [documentation of various options](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#flags-only-supported-by-jqfrepro) that repro supports.

**Comment by zheng-yan-max** [comment]
thank you very much.your information is very useful to me!
