### ISSUE TITLE
Program implementation

### ISSUE THREAD

**Issue by kldr7** [rohanpadhye/JQF#105]
Hello, I would like to ask you whether the target program of fuzzing and the guidance for coverage calculation are located in two threads, and if so, how do they communicate

**Comment by rohanpadhye** [comment]
The guidance lives in the same thread as the entry point of the fuzzed method. However, some guidances (e.g. AFLGuidance) support  fuzz targets that can spawn new threads during test execution (as long as these new threads die before the test method returns).

There is [a global singleton TraceLogger object](https://github.com/rohanpadhye/JQF/blob/90cc50723804d5291afcc7ecda45bdef9946b9e4/instrument/src/main/java/edu/berkeley/cs/jqf/instrument/tracing/TraceLogger.java#L61-L63), and all instrumented code uses static method calls (for performance reasons) to [emit trace events](https://github.com/rohanpadhye/JQF/blob/90cc50723804d5291afcc7ecda45bdef9946b9e4/instrument/src/main/java/edu/berkeley/cs/jqf/instrument/tracing/TraceLogger.java#L76-L78) to this global trace logger. For each thread in the fuzzed target application, there is exactly one corresponding [ThreadTracer](https://github.com/rohanpadhye/JQF/blob/90cc50723804d5291afcc7ecda45bdef9946b9e4/instrument/src/main/java/edu/berkeley/cs/jqf/instrument/tracing/ThreadTracer.java#L105-L111), which saves a reference to the [callback](https://github.com/rohanpadhye/JQF/blob/90cc50723804d5291afcc7ecda45bdef9946b9e4/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/guidance/Guidance.java#L168-L187) registered by the guidance. When an instrumented line of code is executed in the fuzzed application, it invokes the corresponding ThreadTracer's [emit](https://github.com/rohanpadhye/JQF/blob/90cc50723804d5291afcc7ecda45bdef9946b9e4/instrument/src/main/java/edu/berkeley/cs/jqf/instrument/tracing/ThreadTracer.java#L120) method with an event object. This event is then sent to the callback (e.g. [ZestGuidance#handleEvent](https://github.com/rohanpadhye/JQF/blob/90cc50723804d5291afcc7ecda45bdef9946b9e4/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/ei/ZestGuidance.java#L901-L909)).

When using guidances like Zest, which currently only support single-threaded fuzz targets, all of this happens in only one thread. 

Hope this helps.

**Comment by kldr7** [comment]
that is to say ,When using guidances like Zest,callbacks are synchronized,Can I understand that？

**Comment by rohanpadhye** [comment]
Yes, that is correct.

**Comment by rohanpadhye** [comment]
FWIW, the older versions of JQF used a separate shadow thread per application thread to handle trace-event callbacks in an asynchronous manner, and we found that the performance was much worse. I'm happy to dig up the old versions if you are interested in this aspect of the design.

**Comment by kldr7** [comment]
Since asynchronous callback performance is unsatisfactory, how to improve the efficiency of zest, such as multithreading? Do you have a general idea of how to achieve this? I'd like to try to improve it

**Comment by rohanpadhye** [comment]
I've tried to squeeze out as much performance as I could, but if you have any better ideas I'd love to hear it. PRs are also welcome! 

PS: The [current performance is not too bad](https://github.com/rohanpadhye/jqf/wiki/Performance-benchmarks). Are you facing any issues with fuzzing particular applications? You can play around with configuration options like `-Dexcludes` and `-Dincludes` to customize which classes get instrumented.

**Comment by kldr7** [comment]
OK, thank you very much for your patience




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rohan Padhye"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 上午8:46
收件人: "rohanpadhye/JQF"<JQF@noreply.github.com&gt;; 
抄送: "2451558977"<2451558977@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rohanpadhye/JQF] Program implementation (#105)





 
I've tried to squeeze out as much performance as I could, but if you have any better ideas I'd love to hear it. PRs are also welcome!
 
PS: The current performance is not too bad . Are you facing any issues with fuzzing particular applications? You can play around with configuration options like -Dexcludesand -Dincludesto customize which classes get instrumented.
