### ISSUE TITLE
Some questions about code coverage

### ISSUE THREAD

**Issue by kldr-design** [rohanpadhye/JQF#110]
Hello, first of all, thank you for your efforts, JQF is very useful, But I have a few small questions to ask you.
I know that JQF uses code coverage as a guide, AFL is about assigning random values to blocks of code, 
and then calculating the xor of both. Is JQF similar?How is the variable iid calculated in the source code

**Comment by rohanpadhye** [comment]
It's not exactly the same, but similar. JQF's [Coverage](https://github.com/rohanpadhye/JQF/blob/master/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/util/Coverage.java) class takes care of using the IIDs. The IIDs are generated by the tracing logic using a combination of the bytecode ID of the jump instruction and an offset or arm of the branch which is being chosen at runtime. Examples include:

https://github.com/rohanpadhye/JQF/blob/master/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/util/Coverage.java

**Comment by rohanpadhye** [comment]
It's not exactly the same, but similar. JQF's [Coverage](https://github.com/rohanpadhye/JQF/blob/master/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/util/Coverage.java) class takes care of using the IIDs. The IIDs are generated by the tracing logic using a combination of the bytecode ID of the jump instruction and an offset or arm of the branch which is being chosen at runtime. Examples include:

https://github.com/rohanpadhye/JQF/blob/0152e82d4eb414b06438dec3ef0322135318291a/instrument/src/main/java/edu/berkeley/cs/jqf/instrument/tracing/ThreadTracer.java#L327

https://github.com/rohanpadhye/JQF/blob/0152e82d4eb414b06438dec3ef0322135318291a/instrument/src/main/java/edu/berkeley/cs/jqf/instrument/tracing/ThreadTracer.java#L344

https://github.com/rohanpadhye/JQF/blob/0152e82d4eb414b06438dec3ef0322135318291a/instrument/src/main/java/edu/berkeley/cs/jqf/instrument/tracing/ThreadTracer.java#L364

https://github.com/rohanpadhye/JQF/blob/0152e82d4eb414b06438dec3ef0322135318291a/instrument/src/main/java/edu/berkeley/cs/jqf/instrument/tracing/ThreadTracer.java#L228

**Comment by kldr-design** [comment]
Thank you very much for your answer ,But I have a little question. How is the bytecode ID calculated？

**Comment by rohanpadhye** [comment]
The 32-bit bytecode IIDs are composed of a randomly generated class ID (10 bits), a sequentially generated method ID (10 bits), and the bytecode offset within the method (12 bits). See [GlobalStateForInstrumentation](https://github.com/rohanpadhye/JQF/blob/master/instrument/src/main/java/janala/instrument/GlobalStateForInstrumentation.java) and its usage in [SnoopInstructionMethodAdapter](https://github.com/rohanpadhye/JQF/blob/master/instrument/src/main/java/janala/instrument/SnoopInstructionMethodAdapter.java).

**Comment by rohanpadhye** [comment]
FWIW, this logic was largely inherited from the Janala instrumentation engine, but seems to work fine for JQF as well.

**Comment by kldr-design** [comment]
thank you
