### ISSUE TITLE
zest

### ISSUE THREAD

**Issue by zheng-yan-max** [rohanpadhye/JQF#111]
Hi author, I am very interested in the deterministic parameter generator of ZEST. Where can I find the code for the deterministic parameter generator? Thank you for your reply.

**Comment by rohanpadhye** [comment]
There isn't really a single place where this is implemented. You might want to see [this wiki page](https://github.com/rohanpadhye/JQF/wiki/The-Guidance-interface) to get a tour of the JQF framework. Of particular interest may be [StreamBackedRandom](https://github.com/rohanpadhye/JQF/blob/master/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/guidance/StreamBackedRandom.java), which subclasses `java.util.Random` and uses bytes from a fixed input stream to produce pseudo-random values. This is used as the SourceOfRandomness for any [junit-quickcheck](https://github.com/pholser/junit-quickcheck) generator; the logic for glueing everything together is in [this file](https://github.com/rohanpadhye/JQF/blob/master/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/junit/quickcheck/FuzzStatement.java
).

Hope this helps.
