### ISSUE TITLE
Build Failures on jqf:fuzz and jqf:repro

### ISSUE THREAD

**Issue by LaurenElizabethFinn** [rohanpadhye/JQF#122]
I am attempting to fuzz the Google Closure Compiler with Zest but when I use 
`mvn jqf:fuzz -Dclass=examples.CompilerTest -Dmethod=testWithGenerator -Dtime=5m`
I am getting a BUILD FAILURE as shown in the image.
![Screenshot from 2020-12-07 15-58-57](https://user-images.githubusercontent.com/25322712/101400806-56c0f400-38c9-11eb-9202-f2a3b23f4465.png)
I am also getting a BUILD FAILURE when I attempt the following -
`mvn jqf:repro -Dclass=examples.CompilerTest -Dmethod=testWithGenerator`
![Screenshot from 2020-12-07 16-28-08](https://user-images.githubusercontent.com/25322712/101401333-1ca42200-38ca-11eb-8946-20733771712b.png)
Any help would be greatly appreciated, thanks

**Comment by rohanpadhye** [comment]
Hey! This looks fine. The error messages seem to reveal what's going on.

For the first command, it looks like fuzzing completed after the 5min timeout and found a failure (i.e., an input that triggered an uncaught exception in the Closure Compiler). Did you see the Zest [status screen](https://github.com/rohanpadhye/JQF/wiki/Fuzzing-a-Compiler#step-3-fuzz-using-default-generator----moderate-code-coverage) for five minutes? When the timeout expires, the plugin signals "failure" if any errors were found, this is similar to when you run `mvn test` and some test fails. If you don't want to see Maven failures when Zest finds a bug, then avoid giving the `-Dtime` option and just kill the process after 5min (e.g. using CTRL+C or your system's native [timeout](https://man7.org/linux/man-pages/man1/timeout.1.html) command). Killing the process will cause the fuzzing to stop silently.

For the second command, the error message indicates that you have not provided an input whose execution you want to reproduce. Use `-Dinput=<file>` where `<file>` is an input saved in the results directory (e.g. in `corpus` or `failures`). The [tutorial](https://github.com/rohanpadhye/JQF/wiki/Fuzzing-a-Compiler#step-5-fuzz-using-js-generator----more-coverage--new-bugs) shows an example of this usage. 

Hope this helps.

**Comment by LaurenElizabethFinn** [comment]
Thank you for your speedy response to my query. As a newcomer to fuzzing and JQF with Zest, I panicked when I seen "Build Failure" and assumed I was doing something wrong. Thanks for your help, I have got it working now.
![Screenshot from 2020-12-11 14-08-33](https://user-images.githubusercontent.com/25322712/101913640-258f3f00-3bbb-11eb-9091-e8e78a591c96.png)

**Comment by LaurenElizabethFinn** [comment]
Thanks for your speedy response to my query. As someone who is new to fuzzing and JQF with Zest, I panicked when I seen "Build Failure". Thanks for your help, I have got it working now. 
![Screenshot from 2020-12-11 14-19-39](https://user-images.githubusercontent.com/25322712/101914359-21175600-3bbc-11eb-9f63-2ee7dc2c1c1b.png)
