### ISSUE TITLE
Provide Gradle plugin for JQF

### ISSUE THREAD

**Issue by Flowdalic** [rohanpadhye/JQF#125]
It would be great if JQF based fuzzing could be simply integrated via a Gradle plugin (akin to jqf-maven-plugin).

Ideally users would just need  to create test drivers under e.g. `src/fuzz/java` which are executed via a `fuzz` target (e.g. `gradle fuzz`).

**Comment by rohanpadhye** [comment]
Completely agree! Pull requests are very welcome. Someone started this in #86 but then the thread died out. Looking for volunteers to implement this (I don't know anything about gradle myself).

**Comment by rohanpadhye** [comment]
👀 https://github.com/mborzenkov/jqf-gradle-plugin
