### ISSUE TITLE
How to testing a server software?

### ISSUE THREAD

**Issue by liever18** [rohanpadhye/JQF#128]
I want to testing a ftp-server software such as anomic_ftp_server. 
In order to run the ftpd, I write 'testftp.java' for JQF.
Because JQF dosen't hava a timeout testing way,  In testftp.java, main thread create a new thread to run the ftpd software. And using join() to control testing time.
join() doesn't kill the child thread. So I using stop() to kill the child thread but still useless.(It's wired)
The fisrt child thread create a socket but doesn't free it. So second thread can't run correctly.  

There is my testftp.java
```
import de.anomic.ftpd.*;
import java.io.*;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.Assume;
import org.junit.runner.RunWith;
import java.util.*;
import java.lang.*;
import java.net.InetAddress;  
import java.net.Socket;  
import java.net.UnknownHostException;  
@RunWith(JQF.class)
public class testftp {

    public static Throwable te = null;
    @Fuzz /* JQF will generate inputs to this method */
    public void testsettings(InputStream ins) throws java.lang.Throwable {
            
            File file = new File("./ftpd.settings");
	    OutputStream os;

	    os = new FileOutputStream(file);
   	    int bytesRead = 0;
   	    byte[] buffer = new byte[8192];
   	    while ((bytesRead = ins.read(buffer, 0, 8192)) != -1) {
    	       os.write(buffer, 0, bytesRead);
   	    }
   	    os.close();

	    te = null;
	    MyThread thread = new MyThread("A", ins);
	    thread.start();
	    try {
		thread.join(100);
	    } catch (Throwable e) {
		throw e;
	    }
	    //thread.interrupt();
	    thread.stop();
	    if (te != null) {
		throw te;
	    }
	    thread = null;
    }
}
class MyThread extends Thread {
	private String name;
	private InputStream input;

	public MyThread(String name, InputStream input) {
		this.name = name;
		this.input = input;
	}         	   
	@Override
	public void run() {
		try {
			String[] args = {};// = new String[4];
			de.anomic.ftpd.ftpd.main(args);
		} catch (Throwable e) {
			testftp.te = e;
		}
	}
}
```

AFL will throw:
```
[-] PROGRAM ABORT : Unable to communicate with fork server (OOM?)
         Location : run_target(), afl-fuzz.c:2435
```

jqf.log:
```
-------------------------------------------------------------------------------
FATAL ERROR: Address already in use (Bind failed) - probably root access rights needed. check port number
```

My goal is testing a complete java software and this software will not quit by itself like server-software.
I also tried Runtime.getRuntime().exec() but it can't get the coverage information.
Is there a way to achive my goal?

**Comment by rohanpadhye** [comment]
Are you trying to catch timeouts as potential bugs or do you simply want to ignore them during testing? And what kind of timeouts are you expecting, infinite loops or threads stuck waiting for I/O?

You are right that using `Thread.stop()` is a bad idea---in fact, the method is officially deprecated. In Java, killing a running thread is not very easy, and this is not a JQF-specific problem. If a thread is waiting for IO, then `Thread.interrupt()` should cause the blocking method (such as `read()`, etc.) to throw an `InterruptedException` and a well-designed application should get out of its stuck-mode. If a thread is running forever due to an infinite loop, then something needs to throw an exception from that loop to get out of it.

JQF does have a way of detecting timeouts due to long-running loops. I see you are fuzzing with the AFL guidance; in that case, simply give the `-t  TIMEOUT` option (see [docs](https://github.com/rohanpadhye/JQF/wiki/Fuzzing-with-AFL#fuzzing-with-jqf-afl-fuzz)) and AFL will register inputs that exceed that timeout as "hangs". In fact, many of the [infinite-loop bugs ](https://github.com/rohanpadhye/JQF#trophies) found using JQF were using this method. The caveat is that the infinite loop should be in the *instrumented* version of the application, not in external libraries. If you are interested, you can check out the implementation in AFLGuidance... https://github.com/rohanpadhye/JQF/blob/jqf-1.6/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/afl/AFLGuidance.java#L399-L408

Let me know if you were looking for something else or if you have a different type of timeout to handle.

**Comment by liever18** [comment]
> Are you trying to catch timeouts as potential bugs or do you simply want to ignore them during testing? And what kind of timeouts are you expecting, infinite loops or threads stuck waiting for I/O?
> 
> You are right that using `Thread.stop()` is a bad idea---in fact, the method is officially deprecated. In Java, killing a running thread is not very easy, and this is not a JQF-specific problem. If a thread is waiting for IO, then `Thread.interrupt()` should cause the blocking method (such as `read()`, etc.) to throw an `InterruptedException` and a well-designed application should get out of its stuck-mode. If a thread is running forever due to an infinite loop, then something needs to throw an exception from that loop to get out of it.
> 
> JQF does have a way of detecting timeouts due to long-running loops. I see you are fuzzing with the AFL guidance; in that case, simply give the `-t TIMEOUT` option (see [docs](https://github.com/rohanpadhye/JQF/wiki/Fuzzing-with-AFL#fuzzing-with-jqf-afl-fuzz)) and AFL will register inputs that exceed that timeout as "hangs". In fact, many of the [infinite-loop bugs ](https://github.com/rohanpadhye/JQF#trophies) found using JQF were using this method. The caveat is that the infinite loop should be in the _instrumented_ version of the application, not in external libraries. If you are interested, you can check out the implementation in AFLGuidance... https://github.com/rohanpadhye/JQF/blob/jqf-1.6/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/afl/AFLGuidance.java#L399-L408
> 
> Let me know if you were looking for something else or if you have a different type of timeout to handle.

thank you for your reply!
I want to test some server-side programs that will not voluntarily exit. The mutated data is their configuration file, and observe whether the program will run abnormally when processing the configuration file, or cause other effects. Usually these softwares will not be shut down actively after they are started. In order to use fuzzing to test them, I need to shut them down actively.

**Comment by liever18** [comment]
These programs under test will definitely time out, so I don’t care about their timeouts, but hope that they can end their operation after a certain period of time, and then go to the next test of mutated data.

**Comment by rohanpadhye** [comment]
Hmm that sounds tricky if there is no way for the application to terminate normally. Is there some command or message you can send to shut it down? What is the application doing when it does not shut down? Is it waiting/listening for I/O (e.g. a web server waiting for requests) or is it continuously running instructions in a loop (e.g. bitcoin mining)? If it is the latter, then JQF's timeout mechanism will work and a [`TimeoutException`](https://github.com/rohanpadhye/JQF/blob/master/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/guidance/TimeoutException.java) will be thrown from the instrumented bytecode after the `-t <TIMEOUT>` limit is exceeded. If you don't want AFL to mark this as a "hang" but rather consider these sorts of timeouts as a normal operation, then you can actually catch TimeoutException in your test code. For example:

```java
@Fuzz
public void testMethod(InputStream in) {
  try {
     server.run(in);
   } catch (TimeoutException e) {
     // do nothing; return normally
   }
}
```

Note however that this exception will not be thrown if your server is waiting for I/O (e.g. if it is blocked on a network socket). In that case, you should be able to do `thread.interrupt()` to cause the blocked method to exit with an [`InterruptedException`](https://download.java.net/java/GA/jdk14/docs/api/java.base/java/lang/InterruptedException.html). Hopefully, your server lets that exception bubble up to the test method where you can catch it. If the server catches this exception and keeps running, then it means your application is designed never to be stopped, and unfortunately that's going to be hard to handle from JQF then :-(
