### ISSUE TITLE
Hello, I want to fuzzing HBase using JQF. Can JQF fuzzing large programs like HBase? Can I fuzzing the whole program instead of one of its units like AFL? 

### ISSUE THREAD

**Issue by lijunqiang123** [rohanpadhye/JQF#129]
JQF is a great tool that can find lots of Java program bugs.  Can you write a tutorial to show how to fuzzing a large program (such as maven, openjdk) to reproduce a bug?  It will help me a lot. Looking forwrd your reply. Thank you.

**Comment by rohanpadhye** [comment]
Thanks! There is a tutorial on fuzzing the Google Closure Compiler (~0.25 million LoC, though not all reachable at once) available here: https://github.com/rohanpadhye/JQF/wiki/Fuzzing-a-Compiler. It shows how to reproduce a bug as well. Fuzzing HBase should not be a problem and should be similar. JQF has also been used to [fuzz Apache Spark](https://github.com/qianzhanghk/BigFuzz); see the [corresponding paper](https://rohan.padhye.org/files/bigfuzz-ase20.pdf) for the systems' aspects of making this scalable.

**Comment by lijunqiang123** [comment]
Thank you for your reply!
