### ISSUE TITLE
Reusing corpus from previous experiment

### ISSUE THREAD

**Issue by dodoyoon** [rohanpadhye/JQF#136]
Hello, 

I'm aware that I can use `mvn jqf:fuzz -Din=<seeds_dir> ...` option to use corpus from previous experiment. 

However, would it valid to use corpus created from test like below (with two variables fuzz)
`public void testRenderWrappedText(boolean branch, String a)`
for test with new variables like below
`public void testRenderWrappedText(boolean branch, String a, String b)`

There is actually starting seed I would like to set for 'String b', but I'm not sure whether that is possible. Hence, creating this issue. 

It would be helpful if I could just know whether these are possible or not.

**Comment by rohanpadhye** [comment]
Unfortunately, it's not very straightforward to do this. If you use inputs saved from fuzzing the first method with parameters `(bool, String)` as seed inputs for fuzzing a method with params `(bool, String, String)`, then the first two params will be exactly the same as you expect. However, the third param (`String b` in your example) will be generated randomly from scratch.

If you wanted to give some initial value to this string, you will have to edit the saved input file by hand and add the byte values that correspond to the choices in the generator. For example, it looks like the [default String generator](https://github.com/pholser/junit-quickcheck/blob/junit-quickcheck-1.0/generators/src/main/java/com/pholser/junit/quickcheck/generator/java/lang/AbstractStringGenerator.java#L53-L63) first reads a length (four byte int let's call it `len`) followed by `4 x len` bytes containing the content, where each character is a 4-byte int representing the unicode code point. If you put append your saved input file with the bytes corresponding to the unicode string you want, it should work. 

Of course, you can always write your own String generator that uses a simpler encoding, e.g. the [AsciiStringGenerator](https://github.com/rohanpadhye/JQF/blob/jqf-1.7/examples/src/main/java/edu/berkeley/cs/jqf/examples/common/AsciiStringGenerator.java) in JQF expects a four-byte length value `len` followed by `len`  bytes between 0-127 representing ASCII characters. So, the sequence `0x02 0x61 0x61` should correspond to the string of length two: `"aa"`.

Hope this helps.

**Comment by dodoyoon** [comment]
Thank you very much for your help!
