### ISSUE TITLE
Coverage Question!

### ISSUE THREAD

**Issue by pinkhat-m** [rohanpadhye/JQF#137]
Hello again!

I have a question regarding the coverage.
When I run the JQF, it is always started with almost the below values! and also it will be constant for the whole duration of the test!
Total coverage:       14,260 branches (21.76% of map)
Valid coverage:       14,260 branches (21.76% of map)

Remaining as a constant value could be made sense as it cannot go through more path in the app but I suppose it should not be started with these values!
Could you please explain why?

**Comment by rohanpadhye** [comment]
You can run `mvn jqf:repro` with [the flag with `-DlogCoverage=<file>`](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#flags-only-supported-by-jqfrepro) to print the coverage achieved by some of the saved inputs. 

My guess---if this coverage is always present for all inputs---is either from code that is run from your test method before the input is processed, or is run from static initializers of classes. The latter is common in app frameworks that initialize caches or something.

**Comment by pinkhat-m** [comment]
Oh ok, could it be because we have some functions with an annotation such as before,beforeclass in our test? it means that they are run before reaching to JQF point?

But if this is the case why we cannot have more coverage than this?!  while the "cycles completed" will be increasing. Am I missing something?

**Comment by pinkhat-m** [comment]
I have run one input file from the corpus with mvn jqf:repro using the flag -DlogCoverage=<file>, and the only path I can see are just related to the libraries as I could understand!

**Comment by rohanpadhye** [comment]
> Oh ok, could it be because we have some functions with an annotation such as before,beforeclass in our test? it means that they are run before reaching to JQF point?

Yes, that's possible. 

> But if this is the case why we cannot have more coverage than this?! while the "cycles completed" will be increasing. Am I missing something?

I'm not sure. It looks like the coverage instrumentation is working for your program, so you need to debug whether there are any input-dependent control-flow branches or not in your test. I'm guessing you have had success with other tests or with the examples provided in the tutorials. Without seeing your particular test, I cannot say why there is no input-dependent coverage increase. My guess is either your test method is not executing new code based on changes to the input, or the changes to the input required for achieving new coverage are very difficult to achieve by random input generation (e.g. `if (x.equals("FooBar"))` is hard to cover with input `x` because JQF cannot magically construct the string "FooBar".

**Comment by pinkhat-m** [comment]
Thank you, I will try to find why it is like this.

Can I ask you to not close this issue, so I can ask my further questions in the same place? because these days I am just focusing on JQF to apply it on our app. also I am trying to understand everything about JQF.

**Comment by pinkhat-m** [comment]
Regarding the previous discussion, I want to confirm that the coverage instrumentation is working and there is no problem I suppose.
Now I have some questions regarding the outputs(mostly the information of input numbers). I want to check to be sure that I understood them.
I am using the numbers that I have gotten from a test in 50 minutes duration.

1. **"valid inputs"**: 14,074 => this should be all the inputs that JQF used to test the application

2. **corpus("queue size")**: 98 => these are the most suitable inputs based on our application that cover a new path so they are used for applying mutation algorithm to create new inputs(mutated inputs)
* but based on the "fuzz.log" file there are only 12 inputs that make to have a new branches coverage! So I suppose that corpus is not just considering new path coverage, yes? or do I missing something else?

3. **"current parent input"**: 96--->0(after 40m) (I think for this one I need some explanation because I cannot see why it went back to zero!)

4. using flag **"printArgs"**: I got just 19 inputs => unfortunately, I cannot see this number which is not matched with any results that I got.

5. At the end of the test: I had this message "Fuzzing resulted in the test failing on 1005 input(s)."==> this number is related to invalid inputs but I cannot see why we have it as long as we are using a generator for having valid syntactical inputs. Could you please tell me which kind of invalid things could happen?

6. in the **"plot_data"** file:
**"paths_total"** is exactly our queue size?

**"unique_crashes"** is our failures?

**"unique_hangs"**: Can be generated by Zest or it is just for AFL? And I would like to know how I can have them in a different folder if I can get them by Zest? 

7. Another point that does not make sense to me is that I used the "-DlogCoverage" flag for two different inputs from the corpus(the first one and input 80 because of the coverage information that I have in the log file as below)
```
# Cycle 1 completed.
Here is a list of favored inputs:
Input 0 is responsible for 14161 branches
Input 1 is responsible for 64 branches
Input 8 is responsible for 16 branches
Input 13 is responsible for 1 branches
Input 17 is responsible for 1 branches
Input 25 is responsible for 1 branches
Input 43 is responsible for 7 branches
Input 51 is responsible for 1 branches
Input 75 is responsible for 3 branches
Input 77 is responsible for 10 branches
Input 79 is responsible for 1 branches
Input 80 is responsible for 3 branches
Total 14269 branches covered
```

I expected to have different outputs as reaching input 80 give us more coverage(number of branches), but the two outputs are completely the same. Could you please tell me why? 

Thank you in advance.

**Comment by pinkhat-m** [comment]
Regarding the previous discussion, I want to confirm that the coverage instrumentation is working and there is no problem I suppose.
Now I have some questions regarding the outputs(mostly the information of input numbers). I want to check to be sure that I understood them.
I am using the numbers that I have gotten from a test in 50 minutes duration. 

1. **"valid inputs"**: 53,612 => this should be all the inputs that JQF used to test the application

2. **corpus("queue size")**: 90 => these are the most suitable inputs based on our application that cover a new path so they are used for applying mutation algorithm to create new inputs(mutated inputs)
* but based on the "fuzz.log" file there are only 12 inputs that make to have a new branches coverage! So I suppose that corpus is not just considering new path coverage, yes? or do I missing something else?

3. **"current parent input"**: I think for this one I need some explanation because it is always changing!

4. **"Cycles completed"**: what is this?

5. At the end of the test: I had this message "Fuzzing resulted in the test failing on 3577 input(s)."==> this number is related to invalid inputs but I cannot see why we have it as long as we are using a generator for having valid syntactical inputs. Could you please tell me which kind of invalid things could happen?

7. in the **"plot_data"** file:

**"paths_total"** is exactly the same number as our queue size! but why? I mean why the name is like this?!

**"unique_crashes"** is our failures?

**"unique_hangs"**: Can be generated by Zest or it is just for AFL? And I would like to know how I can have them in a different folder if I can get them by Zest? 


Thank you in advance.

**Comment by pinkhat-m** [comment]
I have another question regarding debugging.
In the last part of this link "[Fuzzing a Compiler](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-a-Compiler)"  you mentioned that we could easily debug our test like JUnit test but actually applying @Fuzz will remove Run/Debug options, so how is that possible? (I am using vscode)

**Comment by fuzz** [comment]
You could try tagging GitHub user @fuzz to see if he can debug it for you, but I hear he’s quite expensive.

**Comment by rohanpadhye** [comment]
@pinkhat-m 


> 1. **"valid inputs"**: 53,612 => this should be all the inputs that JQF used to test the application

Correct. These are all inputs that resulted in the test method being executed and returning normally without exception.

> 2. **corpus("queue size")**: 90 => these are the most suitable inputs based on our application that cover a new path so they are used for applying mutation algorithm to create new inputs(mutated inputs)
> 

Correct.

> * but based on the "fuzz.log" file there are only 12 inputs that make to have a new branches coverage! So I suppose that corpus is not just considering new path coverage, yes? or do I missing something else?
>

Correct. Zest borrows a heuristic from AFL where if the same code branch is executed a different binary-order-of-magnitude number of times, it is considered new coverage. This is used to distinguish inputs that execute a loop say 1 times, 2 times, 3-4 times, or 17-32 times, 513-1024 times, etc. all as different "coverage".  You can disable this by setting `-Djqf.ei.DISABLE_SAVE_NEW_COUNTS=true`. 

> 1. **"current parent input"**: I think for this one I need some explanation because it is always changing!

It's the ID of the input from the queue that is currently being mutated. It will always keep changing.

> 2. **"Cycles completed"**: what is this? is it related to the queue? it means that in every cycle, all the inputs in a queue are tested?

Yes. In each cycle, all inputs in the queue have been mutated some number of times. At the end of the cycle, Zest goes back to mutating the first saved input. In most cycles, the size of the queue increases before you cycle back to the beginning. If you go through many cycles without saving new inputs, it is an indication that fuzzing has saturated and you can CTRL+C if you wish to do so.

> 3. At the end of the test: I had this message "Fuzzing resulted in the test failing on 3577 input(s)."==> this number is related to invalid inputs but I cannot see why we have it as long as we are using a generator for having valid syntactical inputs. I think invalid means failing in our assert test driver yes? could it be related to other things also?

The message means your test method threw an exception for those many inputs. Test failure means that there is possibly a bug in your application (or your test). These inputs are saved under the `failures` directory and can be repro'd to see what went wrong.

Just to clarify, these are not invalid inputs. Invalid inputs are not test failures. Invalid inputs are those that resulted in an `assume()` statement not being satisfies. It is possible for a generator to generate syntactically valid inputs by construction, but the input may not satisfy the semantics specified by `assume()` predicates.

> 4. in the **"plot_data"** file:
> 
> **"paths_total"** is exactly the same number as our queue size! but why? I mean why the name is like this?!
> 
> **"unique_crashes"** is our failures?
> 
> **"unique_hangs"**: Can be generated by Zest or it is just for AFL? And I would like to know how I can have them in a different folder if I can get them by Zest?
> 

Yes to all. The `plot_data` file uses the same column names as AFL and it's main purpose is to be compatible with [afl-plot](https://manpages.ubuntu.com/manpages/bionic/man1/afl-plot.1.html). It therefore uses AFL's terminology such as paths, crashes, and hangs... these are not terms used by JQF/Zest elsewhere. 

I believe Zest currently stores crashes/hangs in the same folder: `failures`. From a Java testing point of you, both timeouts and unexpected exceptions are test failures meaning some action is needed. If all tests succeed, then there is nothing to worry about.

---

Btw, fuzz.log logs each saved input and provides a reason for why that input was saved. Inputs that are saved due to new coverage have a suffix +cov those that were saved due to the loop counts have +count; inputs that are valid have +valid; finally, +crash and +hang distinguish the failures respectively.  An input can have more than one reason for why it was saved.

**Comment by rohanpadhye** [comment]
All your questions are great, and it makes me realize that there is a bunch of stuff that's not super well documented, because most previous users of JQF were already familiar with AFL. I should probably document JQF terminology and options for non-AFL users.

**Comment by pinkhat-m** [comment]
Thank you so much for your answers.
Yes, actually I know a little about AFL, not exactly the details. When I realized that for our input(JSON structure) I should work with JQF+Zest, so I just started to explore Zest more deeply.
Could you please tell me about the debugging question?

**Comment by rohanpadhye** [comment]
In IntelliJ IDEA, you can just run/debug a fuzz target like a regular JUnit test.

**Comment by rohanpadhye** [comment]
In IntelliJ/IDEA, you can just run a fuzz target like a regular JUnit test. See screenshot below:

![image](https://user-images.githubusercontent.com/4233266/117194224-d3d99200-adb1-11eb-8601-e8c196511fd1.png)


I don't know why vscode doesn't recognize it. An `@Fuzz` test is a valid regular JUnit 4 test. It is also executed by default without coverage when you run `mvn test`. Maybe this is a configuration issue or a bug in vscode?

**Comment by rohanpadhye** [comment]
If you remove the `@Fuzz` annotation and parameters, are you able to run/debug this from vscode? If yes, then it shouldn't change when you add parameters or the `@Fuzz` annotation.

**Comment by pinkhat-m** [comment]
Just when I put `@Test` I could see run/debug, but we cannot have two annotations for a method.
And for a normal JUnit test method, I could do debugging.

**Comment by rohanpadhye** [comment]
What happens if you annotate with `@Property` from junit-quickcheck?

**Comment by pinkhat-m** [comment]
It only works for normal junit test, not for fuzzing.

**Comment by pinkhat-m** [comment]
Hello, I have a question.
In the paper of JQF somewhere is mentioned: 
> Fuzzing continues either until it is explicitly stopped, until a userspecified timeout expires, or until a test failure is encountered.

I cannot see the last one, because I suppose this failure is not the same as failure folder, because in this case JQF continues its job. Could you please explain in more details what kind of "test failure(s)" it could be?

**Comment by rohanpadhye** [comment]
If you give the property `-DexitOnCrash` to the `mvn jqf:fuzz`, then fuzzing will stop when the first failure is found. There are a bunch of such properties in the plugin that you can read about with `mvn help:describe -Dplugin=jqf -Ddetail`.

**Comment by pinkhat-m** [comment]
oh yes! I totally forgot about that option! Sorry.

**Comment by pinkhat-m** [comment]
Hello,
I could see "Parametric-based" definition from the example on Zest paper, but could you please tell me what is the definition of "Property-based"? maybe by giving an example.

**Comment by rohanpadhye** [comment]
I don't think the [Zest paper](https://rohan.padhye.org/files/zest-issta19.pdf) uses the term "parametric-based" anywhere. It does use the adjective "parametric" for _generators_ . Traditional generators for property-based tests simply perform random sampling of syntactically valid inputs, whereas parametric generators (as defined in the Zest paper) instead decode a sequence of parameter bytes into a syntactically valid input.

The term "property-based" is generally used as an adjective for the test. Property-based testing simply means that it is a test that checks a property that holds over a range of inputs, as opposed to a traditional unit test that hard-codes inputs/outputs. You can read the [Quickcheck paper](https://doi.org/10.1145/1988042.1988046) to get an idea of the original tests that used this style.

**Comment by pinkhat-m** [comment]
Sure, thank you.

**Comment by pinkhat-m** [comment]
Hello,

I have a JSON generator, and for producing random string instead of using
```
identifier = random.nextChar('a','z') + "_" +identifiers.size();
```
which is a simple string, I tried to use the below one to have more different kinds of characters
```
identifier = new  String(gen().type(String.class).generate(random , status));
```
But I suppose apparently, Zest does not accept it, could you please tell me why? what could be the problem?

Respectfully,
Mahdis.

**Comment by rohanpadhye** [comment]
What do you mean by "Zest does not accept it"? Do you get an exception or other error message?

**Comment by pinkhat-m** [comment]
Oh sorry, the problem is not about Zest, I guess!

**Comment by pinkhat-m** [comment]
Hello,
Do you know the relationship between "total paths" and "current path" in the plot? because they do not match together if both are talking about a real "path"!
![high_freq_JQF](https://user-images.githubusercontent.com/47392860/121706095-974a3600-cad5-11eb-8103-b26091432d71.png)

**Comment by rohanpadhye** [comment]
This is not a plot created by JQF. This looks like the output of the AFL-plot utility. AFL uses a confusing terminology of "paths" to refer to seed inputs that are saved in its fuzzing queue. So, the "current path" most likely refers to the ID of the seed input that is being mutated, and "total paths" as the size of the fuzzing queue. Therefore, the "total paths" increase monotonically whereas the "current path" cycles through the range [0, total_paths]. See https://github.com/google/AFL/tree/master/docs for more AFL docs.

**Comment by pinkhat-m** [comment]
Oh, I thought that this plot provides coverage information.
You are right, I did not realize this part before, "number of test cases ("paths")".
Thank you for your response.

**Comment by pinkhat-m** [comment]
Is there any documentation why AFL is using bitmap?

**Comment by rohanpadhye** [comment]
I pointed you to AFL docs above (e.g.  see [technical_details.txt](https://github.com/google/AFL/blob/master/docs/technical_details.txt))---I'm not sure what about the bitmap you are looking for. Do you have a specific question about using JQF with AFL?  Note that I am not the author of AFL. You can ask AFL questions at https://github.com/google/AFL or the [afl-users](https://groups.google.com/g/afl-users) mailing list.

**Comment by pinkhat-m** [comment]
Sure, you are right. Sorry about that.
Respectfully,
