### ISSUE TITLE
[Q] Is AFL++ supported?

### ISSUE THREAD

**Issue by mdindoffer** [rohanpadhye/JQF#142]
Since AFL is dead, is AFL++ supported as a backend for JQF?

I just tried JQF with AFL++ 2.59d, and that seems to be working.
AFL++ has made some breaking changes in 3.00, but I am not sure if anything breaks API-wise with the AFL proxy.

Is there anything to be aware of when fuzzing via AFL++ (3.00+) with JQF ?

**Comment by rohanpadhye** [comment]
Seems to work on a simple test of fuzzing the Google Closure Compiler (see status screen below). Have you noticed any issues? Also, do you have more info on the breaking changes? I mostly use the Zest engine to fuzz Java programs, so I don't have much experience with recent versions of AFL++. In particular, are there any changes to the forkserver or the way that mutated inputs are sent to the test program?

![image](https://user-images.githubusercontent.com/4233266/121951600-20a57680-cd29-11eb-9850-54d46a8ef9d3.png)
