### ISSUE TITLE
Project not compatible with Java 8

### ISSUE THREAD

**Issue by thakkarparth007** [rohanpadhye/JQF#152]
I was trying to build JQF as per the [wiki](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-Zest). I had Java 8 as the default JDK on my system and it wasn't possible to build with that. The `pom.xml` file specifies the minimum required JDK version as 9. I tried setting it to 8 but that didn't work because the source code uses a `readAllBytes()` method in `InstrumentingClassLoader` which is only available in Java 9.

If this method can be replaced with something compatible with Java 8, then the whole project will become Java 8 compatible. If that's not desirable, could the wiki be updated to require Java 9?

**Comment by rohanpadhye** [comment]
Thanks for pointing this out. I updated the wiki to say Java 9+. Since Java 9 is almost four years old now, it is not an unreasonable requirement.
