### ISSUE TITLE
 Fatal error compiling

### ISSUE THREAD

**Issue by noobLei** [rohanpadhye/JQF#158]
hello, when i use setup.sh ,i get the error .i can't solve it. my maven version is apache-maven-3.6.3
. so I hope you can help me, thanks.

![13O$9$VV%OQO8CL9NRCRWY0](https://user-images.githubusercontent.com/71857725/142728945-8a666e00-a6ee-47ed-82c5-b02e44518b96.png)

**Comment by rohanpadhye** [comment]
Seems similar to #155. Are you using an old version of Java (< 9)?

**Comment by noobLei** [comment]
ok , I solved it with java11.but&nbsp; I get a new error . :(
I still need your help ,thank you for your patience.












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rohanpadhye/JQF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月21日(星期天) 上午7:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rohanpadhye/JQF]  Fatal error compiling (Issue #158)





 
Seems similar to #155. Are you using an old version of Java (< 9)?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
