### ISSUE TITLE
JQF for Kotlin

### ISSUE THREAD

**Issue by ankushdesai** [rohanpadhye/JQF#162]
Has someone used JQF for Kotlin? Can you please provide any pointers.

**Comment by rohanpadhye** [comment]
We have used JQF for fuzzing Scala programs (see the [Scala-chess example](https://github.com/rohanpadhye/JQF/blob/master/examples/src/test/java/edu/berkeley/cs/jqf/examples/chess/FENTest.java)), and hope that it works for anything that compiles to bytecode reasonably well. I don't have a Kotlin example published.

I know @aoli-al has written JQF drivers in Kotlin. Not sure if any of the fuzz targets were Kotlin. Can you comment, @aoli-al ?

**Comment by rohanpadhye** [comment]
Oh yeah, we've fuzzed the ChocoPy compiler which uses components written in Kotlin (e.g. [Venus](https://github.com/chocopy/venus)). I believe the instrumentation works fine. However, in this case the main APIs being invoked from the test harness were still Java. 

Usually, the most challenging thing when working with non-Java code that compiles to bytecode is to find out the actually method name to invoke. For example, the scala-chess example invokes a `$less$less` method which I'm guessing is some sort of operator overloading:
https://github.com/rohanpadhye/JQF/blob/jqf-1.7/examples/src/test/java/edu/berkeley/cs/jqf/examples/chess/FENTest.java#L66

**Comment by aoli-al** [comment]
I haven't fuzzed any Kotlin targets. However, writing generators/drivers in Kotlin is possible and is very similar to what you have done in Java.
