### ISSUE TITLE
Fail to fuzzing with Zest

### ISSUE THREAD

**Issue by SicongCao** [rohanpadhye/JQF#168]
When i try to fuzz the test case in the tutorial with zest, it fails.
![image](https://user-images.githubusercontent.com/72129157/146142759-c8dbf9e7-3e71-44b1-9d00-67a07d668d17.png)
My java version is 11 and my maven version is 3.6.2

**Comment by rohanpadhye** [comment]
Hello. This is not an error. It's simply a warning about having no logging implementation for SL4J. Fuzzing should continue to work despite this warning.

**Comment by SicongCao** [comment]
> 你好。这不是错误。这只是关于 SL4J 没有日志记录实现的警告。尽管有这个警告，模糊测试应该继续工作。

Thanks! I have solved this problem by introduing slf4j.simple.

**Comment by SicongCao** [comment]
> Hello. This is not an error. It's simply a warning about having no logging implementation for SL4J. Fuzzing should continue to work despite this warning.

Thanks! I have solved this warning by introducing additional slf4j.simple dependcy.
