### ISSUE TITLE
JQF requires Java 9+ since release 1.8

### ISSUE THREAD

**Issue by anuraaga** [rohanpadhye/JQF#172]
I have a feeling this wasn't intended, as we'd expect to at least target Java 11 or 17, not 9 :)

I think because of this line, the build is generating a library targeting Java 9
https://github.com/rohanpadhye/JQF/blame/cade82293b9a5060e8800adac4ceec5798178575/pom.xml#L142

This results in an error like this when running on Java 8

`Caused by: java.lang.UnsupportedClassVersionError: edu/berkeley/cs/jqf/fuzz/Fuzz has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

class file 53.0 is for Java 9

If it is intended to raise the floor, it should be with a 2.x release, but I suspect newer features aren't be used and it's just a build configuration issue.

**Comment by rohanpadhye** [comment]
You are right that JQF 1.8 requires at least Java 9 to build. Java 8 was released in 2014 and reached end of public updates in 2019, so I don't expect it to be in active use by anyone building JQF.

We could target Java 11 or 17, but we're currently just targeting the oldest version with which everything builds.  There's no change to the public API of JQF, so the major version is not yet bumped; though a 2.x release is on the cards.

Note that JQF should still be able to fuzz targets that are themselves compiled with very old versions of Java.

**Comment by anuraaga** [comment]
@rohanpadhye My issue is about not being able to use JQF from Maven Central with my Java 8 app. This is most likely because release is causing the target bytecode to be Java 9 compatible.

**Comment by rohanpadhye** [comment]
Yes, that's intentional. The current version depends on JDK methods that were only introduced in Java 9, and so will not work with a Java 8 app.

**Comment by rohanpadhye** [comment]
Whether updating a language/runtime requirement implies a major version update (e.g. 2.x as you suggested in your original post) is an interesting point, though, and has made me think. 

Semantic Versioning (at least as of [2.0.0](https://semver.org/spec/v2.0.0.html)) does not appear to offer any opinions on this matter. Major version update is only required for [breaking changes to the public API](https://semver.org/spec/v2.0.0.html#spec-item-8), but [not updates to own dependencies](https://semver.org/spec/v2.0.0.html#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api). It is not clear to me how updates to language or run-time dependencies required of clients should be handled.

From a quick glance at projects that are more widely used than JQF, it looks like language requirements do get updated with minor version updates. For example, Apache Spark updated from Java 7 to Java 8 requirement from [2.1.0](https://spark.apache.org/docs/2.1.0/) to [2.2.0](https://spark.apache.org/docs/2.2.0/), and similarly updated Python requirements across [3.0.0](https://spark.apache.org/docs/3.0.0/) and [3.2.0](https://spark.apache.org/docs/3.2.0/).  Jacskon updated its target Java version across versions [2.6](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.6.0/jackson-databind-2.6.0.pom) and [2.7](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.7.0/jackson-databind-2.7.0.pom). Hmmm.

**Comment by anuraaga** [comment]
Thanks for confirming the version change is intentional, in that case no worries. I've seen a lot of libraries bump major when changing java floor, especially from the still very commonly used Java 8, but it's up to each project. We'll disable our fuzz tests on the java 8 run but keep them on the others.
