### ISSUE TITLE
Auto generation for custom class inputs

### ISSUE THREAD

**Issue by rand-guy** [rohanpadhye/JQF#177]
Hi,
I was trying to test it on custom class input types but it is not allowing to do that without generator. I have observed the below error while trying that:
`java.lang.IllegalArgumentException: Cannot find generator for com.example.sampleproject.controllers.MathControllerTest.test:input of type com.example.sampleproject.controllers.RequestInput`

Is it possible to auto generate input for custom classes the way it is autogenerate for strings, maps etc?

Also, if we are creating generators by coding ourself, how does input become coverage feedback driven? Is it like it observes where and how values are being set in generator and it returns corresponding random.nextInt()/random.nextBoolean() etc accordingly?

**Comment by rohanpadhye** [comment]
You can construct generators automatically for types either by randomly populating values for constructors or by randomly populating values for public fields. See "Implied Generators" in the JUnit-Quickcheck documentation: https://pholser.github.io/junit-quickcheck/site/1.0/usage/other-types.html, along with the `@From(Ctor.class)` and `@From(Fields.class)` annotations. The Junit-quickcheck documentation has lots more info about writing generators.

For both explicit and implicit generators, JQF takes control of calls to `random.nextXYZ()` calls as you indicated, by providing a custom subclass of `java.util.Random` whose values can be recorded, mutated, and replayed. See the [whitepaper](https://rohan.padhye.org/files/jqf-issta19.pdf) or [wiki article](https://github.com/rohanpadhye/JQF/wiki/The-Guidance-interface) for more details.
