### ISSUE TITLE
run jqf in main directory and test directory in command-line

### ISSUE THREAD

**Issue by xxwxxwen** [rohanpadhye/JQF#178]
Dear author, I'm new to jqf. When I run CalendarTest in jqf-examples,it occurred java.lang.ClassNotFoundException:edu.berkeley.cs.jqf.examples.calendar.CalendarTest 
The CalendarLogic.java is in main directory, and CalendarGenerator.java and CalendarTest.java are in test directory.
![3](https://user-images.githubusercontent.com/91888325/153739538-876ee2eb-b079-4cf7-9f2a-18f04342ccf9.png)

![4](https://user-images.githubusercontent.com/91888325/153739396-b511c743-37c7-40b6-96e8-9373a6fd69ed.png)
![5](https://user-images.githubusercontent.com/91888325/153739410-d33048f6-7eab-45a2-88dd-e06d09d01653.png)
When CalendarLogic.java,CalendarGenerator.java and CalendarTest.java are in the same diectory,it could run success in command-line.
When they are in main and test directory(not in the same directory),it occurred an error.

**Comment by Xwen2** [comment]
![2](https://user-images.githubusercontent.com/91888325/153739992-2840791e-3a11-4ca6-aed1-5d46942233af.png)
