### ISSUE TITLE
jqf-afl Timeout while initializing fork server

### ISSUE THREAD

**Issue by xxwxxwen** [rohanpadhye/JQF#181]
Dear author,when I run jqf-afl PngTest example in ubuntu 20.04,with jdk 12.0.1,maven 3.8.3,I couldn't get AFL status screen successfully.I followed as mentioned in [JQF + AFL Pilot Error]#85. I met the similar situation. I tried running on a different machine,but it could still not work.Is it possible that it is not because of the problem of the machine?
![3](https://user-images.githubusercontent.com/91888325/155333906-b29925df-85cf-430b-a118-42c3c80bd9bb.png)
I had also tried as "Can't run "Fuzzing with AFL" example (MacOS) #39",but still failed.
Could you offer any other **jqf-afl test examples** except PngTest can be tried? Thank you very much! Please forgive my poor English.Thank you very much!

**Comment by rohanpadhye** [comment]
Sorry, I'm not sure what else to suggest other than looking at past issues with a similar message (thanks for doing that).  If you can debug this and find an exception or other issue, let me know.

The most actively maintained engine in JQF is the Zest engine, and the Maven fuzzing plugin. Perhaps you can use `mvn jqf:fuzz` instead of the AFL bridge?

**Comment by xxwxxwen** [comment]
Thank you for your reply! Sorry to bother you again, I came across another problem 
1. Is the **ant datase**t (used in zest paper) the same with **ant in JQF test example directory**? When I run ant test example in JQF test directory with mvn 24 hours,the **valid inputs** is 0.00%. I don't know whether this is right?
![ant_testWithString](https://user-images.githubusercontent.com/91888325/158544043-bdc54f03-4ec3-4481-b099-1988c8d8cd0d.png)

2. When compile ant in command line,it seems to need to add dependency.I don't know how to add and compile ant successfully in command line.
![problem_edit_12277398208021](https://user-images.githubusercontent.com/91888325/158547711-af6fc300-b3cd-4e58-9f97-6bbcadd87c17.png)
