### ISSUE TITLE
Transform JQF into a directed fuzzing

### ISSUE THREAD

**Issue by qinhuaian** [rohanpadhye/JQF#187]
Is it feasible to do so?

**Comment by qinhuaian** [comment]
> I don't know what you mean by "feasible" to "transform". JQF currently does not have a directed fuzzing mode. If you would like to contribute such a feature, pull requests are welcome.

Ok，thank you！

**Comment by SicongCao** [comment]
> > I don't know what you mean by "feasible" to "transform". JQF currently does not have a directed fuzzing mode. If you would like to contribute such a feature, pull requests are welcome.
> 
> Ok，thank you！

I'm also exploring the possibility of integrating directional fuzzy testing in JQF. Do you have any good ideas？
