### ISSUE TITLE
I converted the build to Gradle, should i PR?

### ISSUE THREAD

**Issue by stheid** [rohanpadhye/JQF#195]
I find maintainance with maven a hastle and for my own understanding i converted the build to gradle in my local repo.

I am just asking if there is interest to convert the project to gradle than i could make a clean PR where i only change the build files.

If not thats also ok.

**Comment by rohanpadhye** [comment]
Thanks for the note, but I prefer to keep the project building with Maven, which I have a better understanding of. 

FWIW, there's an externally available Gradle plugin for using JQF to fuzz other projects that use Gradle: https://github.com/mborzenkov/jqf-gradle-plugin
