### ISSUE TITLE
JQF-AFL Fork server handshake failed

### ISSUE THREAD

**Issue by xxwxxwen** [rohanpadhye/JQF#199]
Dear author, jqf-afl could run a few days ago. But today when I run on bcel dataset, it occurred this error. It seems jqf-afl could also not work on other datasets. I'm not sure why this happened.
<img width="578" alt="2" src="https://user-images.githubusercontent.com/91888325/181906608-7c5455aa-162a-4672-9f5f-ef6b2f612057.PNG">
I

**Comment by rohanpadhye** [comment]
If it could run before but not now, then there must be a system-specific config issue. Try using the verbose mode (`-v`), which should dump info in a file called `afl.log`.

In general, the JQF-AFL interface is not actively maintained. It should still work, but I won't have the resources to help debug or fix things with it. Most users of JQF use the Zest fuzzing engine via the Maven plugin (`mvn jqf:fuzz`) or the `jqf-zest` command-line runner.
