### ISSUE TITLE
some questions about dataset

### ISSUE THREAD

**Issue by xxwxxwen** [rohanpadhye/JQF#207]
I'm not farmilar with ant. I don't know whether it is correct to use source code to build call graph for ant ? Since it may fail to build call graph for some classes and analysis class hierarchy correlation. Does it need to use binary code to build call graph. How to **build call graph for ant** and **analysis the invoke chain**? I do not have a good understanding of ant.

**Comment by rohanpadhye** [comment]
Hello. There is no call graph and invocation analysis being performed in JQF. I do not know anything about Ant internals either, sorry. Perhaps you want to ask questions about Ant on their mailing lists? If you are trying to build call graphs, you will need to use a static analysis framework such as [Soot](https://github.com/soot-oss/soot/). 

This does not appear to be a question related to JQF, so I am closing this issue.
