### ISSUE TITLE
Query related to reading the generated test cases and entrypoint of cli commands

### ISSUE THREAD

**Issue by mmaashraf** [rohanpadhye/JQF#232]
Hi,

Bear with me as I am trying to learn your tool.

1. I am trying to use your tool, and I would like to know how may I read the test cases that were generated, and stored in `/fuzz_results/<>/corpus/<id>`

<img width="1223" alt="image" src="https://github.com/rohanpadhye/JQF/assets/37049007/eb98cf0b-aa33-4bf6-acc4-48e882fb8eae">

2. Also, Could you share what's the entry point for commands like 
`mvn jqf:fuzz -Dclass=edu.berkeley.cs.jqf.examples.closure.CompilerTest -Dmethod=testWithGenerator`

3. what is the difference between files stored in directories `/corpus ,  /failures.`
Thanks for your time.
Ali

**Comment by rohanpadhye** [comment]
Hi,

Thanks for your interest in JQF. The files are not human readable. See issue #88 for a longer discussion on what to do with these files.

The files in `corpus` correspond to test inputs saved by JQF during its search. Each file corresponds to an input that discovers new code coverage. So, the union of all inputs will be the test suite with maximum coverage that JQF could find.

The files in `failures` correspond to test inputs saved by JQF which led to assertion failures or other unexpected exceptions. If you repro with any of these files, you should see a stacktrace with the relevant exception. JQF does its best to avoid duplicate failures stemming from the same underlying issue, but in general it cannot promise to do so.
