### ISSUE TITLE
'Too many trials without coverage' error

### ISSUE THREAD

**Issue by manobaneru** [rohanpadhye/JQF#235]
Good evening!

I'm trying to fuzz my project. It was originally build with Ant, but I've created `pom.xml` with all dependencies specially to use mvn jqf:fuzz.
And when I run this commands, JQF starts working for 5-10 seconds and then shows `'Too many trials without coverage; likely all assumption violations'`. I've seen similar issue but i didn't really solved my problem. And I don't really understand why,
![image](https://github.com/rohanpadhye/JQF/assets/72031386/abee5137-cf82-4ea6-bf2f-42ce9da4a9df)
![image](https://github.com/rohanpadhye/JQF/assets/72031386/3a75037b-bf5d-42bd-98cb-27d85c4cd534)

I would be really glad if you could help me.

**Comment by rohanpadhye** [comment]
It seems that there is no test coverage being achieved in any execution, but there are 2 unique failures. This is usually an indication that the test is not being executed properly; instead, it is failing instantly. To debug, try using `mvn jqf:repro` to run your test with a single input (you'll need to add an additional `-Dinput=<file>` argument; use one of the files from `corpus/failures`). Most likely there will be an exception like `ClassNotFound` or similar that is preventing your test from being executed correctly. Check classpaths, etc. and try again. Use print statements or similar to make sure that your test code is actually being run. Once the repro succeeds properly, then you can try fuzzing again.

Alternatively, start with the demo project: https://github.com/rohanpadhye/jqf-zest-example, which should work as per the README, and make small modifications to it to add your code. You will be able to identify the exact step that causes an issue if you start with a working fuzzer and then add your own test code.

**Comment by manobaneru** [comment]
Thank you for your answer!
