### ISSUE TITLE
Repro without maven plugin

### ISSUE THREAD

**Issue by enzocardeal** [rohanpadhye/JQF#241]
Hi,

I'm trying to get the fuzzer code coverage via IntelliJ but it is not possible for Maven dependent runs. Is there a way to invoke "jqf:repro" action without the plugin?

Best Regards,
Enzo

**Comment by rohanpadhye** [comment]
Yes, there is a runnable script [`bin/jqf-repro`](https://github.com/rohanpadhye/JQF/blob/master/bin/jqf-repro). You will have to provide a full classpath when using this script. Run it without any options to see usage.
