### ISSUE TITLE
the https://raw.githubusercontent.com/ornicar/lila-maven/master/org/lichess/scalachess_2.12/8.6.8/scalachess_2.12-8.6.8.pom refuse connection

### ISSUE THREAD

**Issue by zhao-yuanjie** [rohanpadhye/JQF#245]
the https://raw.githubusercontent.com/ornicar/lila-maven/master/org/lichess/scalachess_2.12/8.6.8/scalachess_2.12-8.6.8.pom refuse connection，so I can't install the jqf successfully.

**Comment by rohanpadhye** [comment]
Hi, I just tried reinstalling JQF and this connection works fine for me. If I click the link in your issue, I can see the POM file as; don't you? Do you perhaps have a firewall or other network entity that is preventing the connection?

As a workaround, you can install JQF without the examples by running the command:
```
mvn install -pl '!examples'
```
