### ISSUE TITLE
Unable to use JQF with Maven Project built on JDK 8?

### ISSUE THREAD

**Issue by silveryu1999** [rohanpadhye/JQF#248]
Hi author. If we have a maven project which uses JDK 8, is it no other way to fuzz it with JQF (which requires JDK 9) unless we update the project? I've read some related issues, just to confirm it.

**Comment by rohanpadhye** [comment]
Yes, I believe so. Java 9 was released about seven years ago and the current version is Java 21. There is no reason for any project to continue to use Java 8, which Oracle itself has stopped supporting. So, unfortunately, JQF will not support such an ancient version.
