### ISSUE TITLE
JDK 21 - Dynamic Loading of Agent  limit

### ISSUE THREAD

**Issue by rogeriob2br** [rohanpadhye/JQF#260]
#https://github.com/rohanpadhye/JQF/issues/141

Just like the version 16 error described in issue 141, I'm experiencing the same problem that apparently should be fixed with "-XX:+EnableDynamicAgentLoading", but it had no effect.

![image](https://github.com/user-attachments/assets/7811a043-317c-482a-b1fa-9e05b239c566)

Apparently it reached an agent limit.
I searched for the error, and for the warning that Dynamic Loading agents will be disabled, and found an issue in mockito:
#https://github.com/mockito/mockito/issues/3037

From the description, libraries could no longer use agents without -javaagent

Is there any way to fix it?

**Comment by aoli-al** [comment]
This error issue may not be caused by instrumentation. The warning you saw was benign. 

The output says, `Valid inputs: 0(0.00%)`, which should be the issue. You may check the implementation of the generator and verify if it can generate valid inputs.

**Comment by rohanpadhye** [comment]
@rogeriob2br Did @aoli-al's comment help you out? I just tried JQF on both Java 21 and Java 22 and everything works fine for me with the examples in the repo.

**Comment by rogeriob2br** [comment]
Yes, I was really making mistakes in the test.

**Comment by rohanpadhye** [comment]
Thanks for confirming!
