### ISSUE TITLE
Update the version available in maven.org

### ISSUE THREAD

**Issue by pachulo** [rohanpadhye/jqf#28]
Latest version available in maven.org is `alpha2`:

- https://search.maven.org/search?q=g:edu.berkeley.cs.jqf%20AND%20a:jqf-maven-plugin&core=gav

Shouldn't it be updated to `alpha3`?

**Comment by rohanpadhye** [comment]
Thanks for point that out. I don't know why alpha-3 wasn't deployed. Perhaps I forgot (I guess most users were simply cloning from the repo?).

Anyway, I've deployed alpha3 just now and will be releasing beta1 soon. It may take a while for it to show up on all the repositories. Thanks again!

**Comment by carolemieux** [comment]
@rohanpadhye you may want to update the pom.xml snippets in the README.md and the wiki to show the current version once it's deployed

**Comment by pachulo** [comment]
It's up now! Thanks!
