### ISSUE TITLE
Error when building jqf-examples (org.lichess:scalachess_2.12:jar:8.6.8)

### ISSUE THREAD

**Issue by pachulo** [rohanpadhye/jqf#29]
When building with `$ jqf/setup.sh` I got this error:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] jqf ................................................ SUCCESS [  0.003 s]
[INFO] jqf-instrument ..................................... SUCCESS [  5.486 s]
[INFO] jqf-fuzz ........................................... SUCCESS [  7.941 s]
[INFO] jqf-maven-plugin ................................... SUCCESS [  2.638 s]
[INFO] jqf-examples ....................................... FAILURE [01:10 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:27 min
[INFO] Finished at: 2018-09-18T14:27:25+00:00
[INFO] Final Memory: 37M/530M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jqf-examples: Could not resolve dependencies for project edu.berkeley.cs.jqf:jqf-examples:jar:1.0-beta-1-SNAPSHOT: Could not find artifact org.lichess:scalachess_2.12:jar:8.6.8 in mirror (https://uk.maven.org/maven2/content/groups/public) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jqf-examples
```

**Comment by rohanpadhye** [comment]
Hello. Your build seems to have trouble downloading `scalachess` from the lichess repository, which whose URL we have specified in `examples/pom.xml`. It appears that your Maven set up is trying to download the dependencies from the UK central mirror instead. Have you customized your mirrors in `.m2/settings.xml` or similar and if yes, then is the `mirrorOf` property set to `*`? Such a setting may override any project-specific repositories, such as the repository we have specified to fuzz the `scalachess` example.

Alternatively, if you don't want to run the provided examples then you can skip downloading all of the external dependencies altogether and simply build JQF minus the examples:
```
mvn clean package -pl !examples
```

**Comment by pachulo** [comment]
Well, you are right about the downloading. Thanks a lot!

By the way, to build JQF minus the examples I had to escape the `!` like this:

`$ mvn clean package -pl \!examples`

**Comment by rohanpadhye** [comment]
Good to know. I guess the escaping mechanism depends on the shell (e.g. `fish` does not require it).

As a side note (for anyone reading this issue in the future): if using Maven's mirroring options, you can specify the ID of the repository for which the mirror is applicable, e.g. `central` for a mirror of Maven Central. See https://maven.apache.org/guides/mini/guide-mirror-settings.html for more details. Specifying an ID of `*` overrides all explicit repository URLs that may be present in project POMs, such as the `lila-maven` repository that `jqf/examples/pom.xml` specifies to download the `scalachess` example.
