### ISSUE TITLE
mistake in the wiki: Zest maven plugin parameter prefix is missing

### ISSUE THREAD

**Issue by Ahmedfir** [rohanpadhye/jqf#40]
in the wiki, the zest comands are written without the parameters prefixs.
i.e. to fuzz a method of a class the comand should be:

mvn jqf:fuzz -Dclass=com.tuto.zest.CalendarLogicTest -Dmethod=testLeapYear 

but is written:

mvn jqf:fuzz CalendarLogicTest testLeapYear 

Very good library!
Best regards

**Comment by Ahmedfir** [comment]
You’re welcome! I am sorry , I think I made you lose your time, I have used the maven plugin using the parameters as shown in the scripts wiki (without the -D style parameters). When it didn’t work I have looked into the other wiki and have used the -D style parameters. Then I thought that it would be nice to share this with you to fix it in the wiki so that the other people don’t have to face this issue again... but if as you say: the scripts don’t get the parameters in the same way as the maven plugin, then it’s not an issue but just my mistake... may be you could add also the maven plugin commands to that wiki, to improve it... but I think everything is alright and there’s nothing to fix.
Sorry again and thank you for the quick answer !

Cheers 
Ahmed

Envoyé de mon iPhone

**Comment by rohanpadhye** [comment]
No problem. I expanded [the sentence in the wiki](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-Zest#fuzzing-testleapyear) to show the full Maven command. Thanks!
