### ISSUE TITLE
BUG: jqf:fuzz test discovery

### ISSUE THREAD

**Issue by yevgenypats** [rohanpadhye/jqf#45]
I think I've encountered a bug or either I'm doing something wrong.

I've added a simple fuzzing test to [JSqlParser](https://github.com/fuzzitdev/JSqlParser/commit/743f14e937271b3c5c92dc0a56d5b93b6928ac25) library.

The execution of the test via `mvn -Dtest=CCJSqlParserFuzz test` (i.e quickcheck) works fine.
but when I use `mvn jqf:fuzz -Dclass=CCJSqlParserFuzz -Dmethod=testParseExpression` I get the following error:

```
[ERROR] Failed to execute goal edu.berkeley.cs.jqf:jqf-maven-plugin:1.2:fuzz (default-cli) on project jsqlparser: Could not load test class: Cannot find class CCJSqlParserFuzz -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Here are the exact steps to reproduce

```bash
git clone https://github.com/fuzzitdev/JSqlParser
cd JSqlParser
 git checkout fuzzing
docker run -v `pwd`:/jsql -it maven:3.6.1-jdk-8 /bin/bash
cd /jsql

## This works
mvn -Dtest=CCJSqlParserFuzz test

## this doesn't work
mvn jqf:fuzz -Dclass=CCJSqlParserFuzz -Dmethod=testParseExpression
```

cc @rohanpadhye

**Comment by yevgenypats** [comment]
okay found the problem for some reason you have to specify the full class name and it doesn't auto detect it like junit. I guess this is something worth adding.

**Comment by rohanpadhye** [comment]
Thanks for the update. Closing as not a bug. 

Feel free to submit a PR with the suggested feature. However, note that fully-qualified names are the only way to uniquely identify classes in Java. "Auto-detection" can result in ambiguities. JUnit gets around this by running ALL classes that match a given substring. In JQF, we need exactly one class and one method to fuzz.
