### ISSUE TITLE
Exit code on exit

### ISSUE THREAD

**Issue by yevgenypats** [rohanpadhye/jqf#50]
we added the EXIT_ON_CRASH feature which works good but the exit code is always 0 which is a bit weird and I can rely on in a script. I'm not sure were to put this change. should I throw an exception here:

https://github.com/rohanpadhye/jqf/blob/master/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/ei/ZestGuidance.java#L580

**Comment by rohanpadhye** [comment]
I don't think the `Guidance` should directly influence the exit state of the script that is driving the fuzzing session. The `Guidance` simply says that no more inputs are to be generated, which is fine. The fact that the test was not successful can be determined by the JUnit-specific failure collection mechanism: https://github.com/rohanpadhye/jqf/blob/807e6abe4f7018c34ffd443752633807a112a2e4/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/junit/quickcheck/FuzzStatement.java#L183-L190

I believe this does currently cause an exception to be propagated, right? 

https://github.com/rohanpadhye/jqf/blob/807e6abe4f7018c34ffd443752633807a112a2e4/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/junit/quickcheck/FuzzStatement.java#L203-L211

**Comment by yevgenypats** [comment]
Yes this was strange to me as well as this line is being called but the exit code is still 0. maybe junit catches all the exceptions and returns always 0?

**Comment by rohanpadhye** [comment]
The driver scripts such as [ZestDriver.java](https://github.com/rohanpadhye/jqf/blob/807e6abe4f7018c34ffd443752633807a112a2e4/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/ei/ZestDriver.java) currently ignore the return value of [`GuidedFuzzing.run()`](https://github.com/rohanpadhye/jqf/blob/807e6abe4f7018c34ffd443752633807a112a2e4/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/junit/GuidedFuzzing.java#L96), which is a JUnit test result. Perhaps the result could be parsed here to add appropriate exit code?

On the other hand, the Maven plugin does actually propagate the test error:
https://github.com/rohanpadhye/jqf/blob/807e6abe4f7018c34ffd443752633807a112a2e4/maven-plugin/src/main/java/edu/berkeley/cs/jqf/plugin/FuzzGoal.java#L246-L249

**Comment by yevgenypats** [comment]
Oh got it so I'll add the parsing to `ZestDriver.java`. It's good that the maven plugin already does that but the ZestDriver is also handy in some scenarios and on Fuzzit we use him actually.

**Comment by rohanpadhye** [comment]
Yup. I guess it was an oversight, since we never needed an exit code until now. It would be good to make the driver's behavior consistent with the Maven plugin. Thanks for bringing this up.
