### ISSUE TITLE
Guidance Improvment

### ISSUE THREAD

**Issue by yevgenypats** [rohanpadhye/jqf#58]
@rohanpadhye 
While writing a basic example for Fuzzit (an example I always use for other fuzzers) https://github.com/fuzzitdev/example-java#understanding-the-bug 

I saw that it is having hard time finding this bug. maybe we can take some mutation heuristics from go-fuzz or libfuzzer so it will work better with stream of bytes. go-fuzz also use sonar heuristics which is quite powerful and might work well for jqf. but for a start I think this should be detected just by coverage guided and the right mutations. do you have an idea why it is not detected?/what are the current mutations in the case of my example?

**Comment by rohanpadhye** [comment]
Hey. I'm not sure about Go, but I can see why this bug would be much easier to find for C than for Java. Unlike C strings, which are null terminated, Java strings are a pair of length and an array of characters -- at least that's how the default StringGenerator in junit-quickcheck generates strings. Further, each char in Java is 2-bytes long, unlike C strings where each char is 1 byte; therefore, generating `F` at random is probably harder. For this crash to be generated, you essentially need to generate a magic 4-byte value  `3` (for the length) and then also magic 2-byte values `F`, `U`, and `Z`. This seems harder than the equivalent code in C.

Once workaround is to use an Ascii string generator, which restricts each character to be an ASCII value (between `0` and `127`). Here is an updated test driver:

```
    @Fuzz
    public void fuzz(@From(AsciiStringGenerator.class) String data) {
        ParseComplex.parse(data);
    }
```

Now Zest finds the crash in about 10-30 seconds on my laptop.

**Comment by rohanpadhye** [comment]
Note that this example is also not a realistic example from the kind of Java projects that we usually fuzz. These examples work great for C fuzzing tools because everything is about strings and characters, and most fuzz targets are parsers of binary or character data.

In JQF, we mostly target applications like compilers, build systems, databases, etc. where the complexity is not in the sequence of characters but rather in the structure and semantics of the input.

**Comment by yevgenypats** [comment]
Cool that make sense. Thanks for the explanation. I think we can close this issue for now.

**Comment by rohanpadhye** [comment]
@yevgenypats 

If you want a more realistic example, here is a very short test that is also used in the tool paper: https://github.com/rohanpadhye/jqf/blob/d19e89e8b2e5062f7ec414bac8a182ff2b9ecc2d/examples/src/test/java/edu/berkeley/cs/jqf/examples/commons/PatriciaTrieTest.java#L64-L71

Zest generates an input that satisfies the `assume` but fails the `assert` in about 5-10 seconds on my laptop.

This is currently an open bug in Apache Commons that was found using Zest: [COLLECTIONS-714](https://issues.apache.org/jira/browse/COLLECTIONS-714)
