### ISSUE TITLE
improvement: performance improvement in coverage updating 

### ISSUE THREAD

**Issue by Ahmedfir** [rohanpadhye/jqf#62]
In case of 0 coverage the method `edu.berkeley.cs.jqf.fuzz.util.Coverage#updateBits` is anyway executing the full for-loop from 0 to 65535.
@rohanpadhye , may be if a 0 check is added before the for loop the computing performance would be improved in the long run 
i.e. `if (that.counter.nonZeroCount != 0){ for ... }`

**Comment by rohanpadhye** [comment]
Sure, I suppose that sounds reasonable. Please send a PR if it helps. I don't think I've worked with any non-trivial target that gave me zero coverage in a steady state :-)

Have you actually noticed a performance issue because of this?

**Comment by Ahmedfir** [comment]
I will try to do it the next week (or during the weekend).
Honestly, I didn't notice any performance issue, I just thought about it while debugging and reading the code. :p
I think it will be a micro improvement with a micro impact :p :)

**Comment by Ahmedfir** [comment]
could you please give me permission to create a branch so that I can create a pull request. (I have done the fix locally, I just can't push the fix branch: 403 Permission denied... )

**Comment by yevgenypats** [comment]
Hey @ahmedfir:) you can do this with a fork repo. Can you try push it to your repo and open a PR?
