### ISSUE TITLE
Reusing found coverage

### ISSUE THREAD

**Issue by floyd-fuh** [rohanpadhye/jqf#63]
When running JQF-Zest-Maven, how can I reuse the found coverage of a run when running it later again?

**Comment by rohanpadhye** [comment]
Huh. There does not seem to be an option to provide a seed directory yet. Guess I've never needed to do that. However, [Zest does support it](https://github.com/rohanpadhye/jqf/blob/d19e89e8b2e5062f7ec414bac8a182ff2b9ecc2d/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/ei/ZestGuidance.java#L275-L280). We just need to add an option to [call this extended constructor from the Maven plugin](https://github.com/rohanpadhye/jqf/blob/master/maven-plugin/src/main/java/edu/berkeley/cs/jqf/plugin/FuzzGoal.java#L230).

I'll add an `-Dseeds=<dir>` option to start from a given corpus.

There was also some discussion about adding support  for resuming from a saved *output* directory in #55. That might also be nice to have.

**Comment by rohanpadhye** [comment]
Added an option `-Din=<seeds>` for consistency with `-Dout=<results>`
