### ISSUE TITLE
How to get code coverage

### ISSUE THREAD

**Issue by snakefor100** [rohanpadhye/jqf#67]
Hi, The JQF is very beautiful. I integrate the JQF to my project. but i hava some question. How to get the code coverage with ZestGuidance? Do you  hava some example?  I see always 0 when it running. 

I hava readed the paper "https://people.eecs.berkeley.edu/~rohanpadhye/files/zest-issta19.pd". I think it must be run a javaagent when i wanted the coverage data. is that right?

so,i add some command when execute test ,such as "-javaagent:/xxx/jqf-instrument-1.4-SNAPSHOT.jar" . javaagent is running ,but it has some failure.

![image](https://user-images.githubusercontent.com/8774548/66754335-5517be00-eec8-11e9-8f1b-6ae06f756e0b.png)

 "name == this.className", is alway false. make sure there is don't use "name.equals(this.className)"? 

 when i rewrite the code to "equals". there is another Exception...
![image](https://user-images.githubusercontent.com/8774548/66754638-0159a480-eec9-11e9-83ba-64575c6c474a.png)

so....how to get code coverage?  
      thank you for you reading.please help me .

**Comment by rohanpadhye** [comment]
Hi @snakefor100. 

> I hava readed the paper "https://people.eecs.berkeley.edu/~rohanpadhye/files/zest-issta19.pd". I think it must be run a javaagent when i wanted the coverage data. is that right?

You do not have to specify the javaagent yourself. You can run Zest either via the script `bin/jqf-zest` or by using the Maven plugin. Both of these handle launching the instrumentation for you. The `jqf-zest` script will use the appropriate `javaagent` and the Maven plugin will use a custom instrumenting class-loader. Check out the following tutorials:

https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-Zest (shows usage of the `jqf-zest` launcher)
https://github.com/rohanpadhye/jqf/wiki/Fuzzing-a-Compiler (shows usage of the Maven plugin)

The advantage of the Maven plugin is that you do not need to download this repository locally. You can simply add a dependency on JQF via Maven and fuzz your project. The disadvantage is that you cannot instrument JDK classes that are loaded by the bootstrap classloader.

If you want to extend/modify the fuzzing logic, then using `bin/jqf-zest` is probably the best option. Please follow the tutorial and let me know if you have any issues with getting code coverage.

> "name == this.className", is alway false. make sure there is don't use "name.equals(this.className)

This probably looks like a bug. I don't know how this assert never failed until now >_<. Perhaps the `name` was always the same object? Changing that to `equals` seems like a good idea.

**Comment by rohanpadhye** [comment]
What Java version have the target classes been compiled with? I just pushed an update that upgrades the dependency on the ASM bytecode toolkit. Can you tell me if you still see the error after these changes?

**Comment by snakefor100** [comment]
> What Java version have the target classes been compiled with? I just pushed an update that upgrades the dependency on the ASM bytecode toolkit. Can you tell me if you still see the error after these changes?

I retry test case, but still has error. my project use jdk8. i find two error .

1:when the agent runing, it will load many classes, some class is NestHostClass.so it will be run this code:
![image](https://user-images.githubusercontent.com/8774548/66810711-60b7c300-ef62-11e9-97f8-5f3123fc2b65.png)

In the visitNestHostExperimental method, we can see this code：
![image](https://user-images.githubusercontent.com/8774548/66810822-965cac00-ef62-11e9-841e-3dd6e5124ed6.png)

the api is Opcodes.ASM5,it is fixed.
![image](https://user-images.githubusercontent.com/8774548/66810964-d459d000-ef62-11e9-9878-26508b73663d.png)

so ,there is always UnsupportedOperationException when the class is NestHostClass. i don't know  if the error  had any impact, when the error is happened, it  can not  block the agent runing.

2: the second error make me confusion. when the agent runing, it will be has NoClassDefFoundError. it looks like the SingleSnoop class has some error,but i can't find why the error happened.
![image](https://user-images.githubusercontent.com/8774548/66814073-92cc2380-ef68-11e9-8e85-d5b693189d72.png)

when the agent load class to enhance, is that contain jqf'class? if it is , can be exclude? because it looks like unnecessary

**Comment by snakefor100** [comment]
> Hi @snakefor100.
> 
> > I hava readed the paper "https://people.eecs.berkeley.edu/~rohanpadhye/files/zest-issta19.pd". I think it must be run a javaagent when i wanted the coverage data. is that right?
> 
> You do not have to specify the javaagent yourself. You can run Zest either via the script `bin/jqf-zest` or by using the Maven plugin. Both of these handle launching the instrumentation for you. The `jqf-zest` script will use the appropriate `javaagent` and the Maven plugin will use a custom instrumenting class-loader. Check out the following tutorials:
> 
> https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-Zest (shows usage of the `jqf-zest` launcher)
> https://github.com/rohanpadhye/jqf/wiki/Fuzzing-a-Compiler (shows usage of the Maven plugin)
> 
> The advantage of the Maven plugin is that you do not need to download this repository locally. You can simply add a dependency on JQF via Maven and fuzz your project. The disadvantage is that you cannot instrument JDK classes that are loaded by the bootstrap classloader.
> 
> If you want to extend/modify the fuzzing logic, then using `bin/jqf-zest` is probably the best option. Please follow the tutorial and let me know if you have any issues with getting code coverage.
> 
> > "name == this.className", is alway false. make sure there is don't use "name.equals(this.className)
> 
> This probably looks like a bug. I don't know how this assert never failed until now >_<. Perhaps the `name` was always the same object? Changing that to `equals` seems like a good idea.

**Comment by rohanpadhye** [comment]
It looks like the method `visitNestHostExperimental` is deprecated in ASM.  Do you (or does anyone else) know what causes it to be invoked during instrumentation? I have never encountered a class with nested hosts in any of the applications that I have fuzzed before.

**Comment by snakefor100** [comment]
emm..i add some classes to "janala.excludes",then i solve this problem. thank you for your help.Wish the jqf better and better in the future.

finally,i have one suggest, this code:

![image](https://user-images.githubusercontent.com/8774548/67093908-36c20300-f1e5-11e9-831d-31571eecaf79.png)

it looks like the default value is true is better. because i just follow with interest my code, i don't care the coverage of other jar.if the default is false, the agent will load all classes in my classloader to enhance.

**Comment by rohanpadhye** [comment]
The default value is `false` because by default we want to instrument as much as possible, unless the user has explicitly requested excluding some classes.

If the default was `true` for `shouldExclude`, then first-time users would see nothing being instrumented, and it would be very difficult to manually include every single application class/package.

Anyway, thanks for the follow up and update @snakefor100 !
