### ISSUE TITLE
Zest fuzzing has no resume?

### ISSUE THREAD

**Issue by reijin90** [rohanpadhye/jqf#69]
Hey there!

I'm new to Zest and JQF, hence I might have overlooked it, but I can't seem to find any functionality that would allow me to resume fuzzing with the previously created corpus. Once I re-run the fuzzer, it starts from 0 and deletes all previous files. Is there no such functionality in place that allows reuse of corpus data?

**Comment by rohanpadhye** [comment]
If using the Maven plugin, you can give `-Dseeds=<dir>` to use an existing corpus as the starting point. If using the command-line script `jqf-zest`, then it takes the seed inputs as command-line arguments after the name of the test method.
