### ISSUE TITLE
unable to disable console output 

### ISSUE THREAD

**Issue by Ahmedfir** [rohanpadhye/jqf#70]
I have tried to disable console output to check if I would get better performance by using this maven param `-Djqf.ei.LIBFUZZER_COMPAT_OUTPUT=false` but it didn't work. Isn't it the right parameter to use for this purpose? Is there any other way to do it?

**Comment by rohanpadhye** [comment]
If you run Zest without a tty/console, then it should not display any stats. It currently checks `System.console()` exists in order to print stats. Piping stdout to `/dev/null` should work.

@yevgenypats Can you comment on `LIBFUZZER_COMPAT_OUTPUT`?

**Comment by Ahmedfir** [comment]
yes I have checked again in the code, only a null console would prevent/disable the stats printing. `LIBFUZZER_COMPAT_OUTPUT` disables printing in only some cases. 
Do you know any easy/direct way to set the console to null from the maven command (a parameter for example)? Else this may be a good feature to add; i.e. `-DstatsOutput=false` would disable the stats printing by adding a flag that's checked in the same time as the console nullability.

**Comment by rohanpadhye** [comment]
Fair enough. It would be nice to piggy back on Maven's `-q` option, since it also supresses all of Maven's verbose output. I haven't yet figured out how to tell if `-q` flag is given from inside the plugin. Otherwise, `-DstatsOutput=false` also sounds like it could be useful.

Contributions welcome, as always!

**Comment by yevgenypats** [comment]
@rohanpadhye as far as I remember this is like @Ahmedfir said that LIBFUZZER_COMPAT_OUTPUT disabled printing only in some cases and the main `if` is checking if the console is null. I think we need to add another option.

**Comment by Ahmedfir** [comment]
Ok I will start working on it now. 
I will add a boolean maven property `-DstatsOutput=false` as proposed by @rohanpadhye which will disable the console outputs and the fuzzing log. I will not remove console null checks of course. i.e.:
`// before:`
`if (console != null)`
`// now:`
`if (statsOutput && console != null)`

**Comment by Ahmedfir** [comment]
I have some questions:

1. Is it fine if I implement this feature only for the Zest Goal of the maven plugin? (considering that this new parameter is optional and to avoid messing up the parameters order, it would be better/faster for now to implement it just for the zest plugin ...)
2. I tried to test my implementation on the ZestDriver using the scripts as described in the documentation Zest 101, And I am getting a classpath exception... Do you know how to solve it? Or is there any other way to test the zest driver?
`(base) mp0252:IdeaProjects ahmed.khanfir$ cd jqf/examples/
(base) mp0252:examples ahmed.khanfir$ /bin/bash ../bin/jqf-zest -c .:$(../scripts/classpath.sh) DateFormatterTest fuzzSimple`
Here's the exception trace:
`java.lang.ClassNotFoundException: DateFormatterTest
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:416)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:124)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:96)
        at edu.berkeley.cs.jqf.fuzz.ei.ZestDriver.main(ZestDriver.java:77)
`
3. What's the easiest way to test the CLI locally?

Thanks

**Comment by rohanpadhye** [comment]
1. I think supporting the property only for the Maven plugin should be fine for now. It is only in Maven that we need to distinguish between the output of Maven itself and of Zest. When running form CLI, we can just pipe everything to `/dev/null` to avoid output.

2. That seems to be the right command, assuming that `DateFormatterTest.class` is in the current directory (and that you are not using Windows, where the classpath separator is a semicolon). 

3. Alternatively, you can use the script `examples_classpath.sh` from the `scripts` dir, which  expands to the classpath that also contains everything the in the `jqf-examples` directory, such as `edu.berkeley.cs.jqf.examples.jdk.DateFormatterTest` (you have to provide the FQN of the class to test).

**Comment by Ahmedfir** [comment]
1. I will push to a fork and create a pull request
2. I moved to the directory where `DateformatterTest.class` is, I have used the `examples_claspath.sh` script and I used the class reference `edu.berkeley.cs.jqf.examples.jdk.DateFormatterTest` so it worked :
`/bin/bash /path/to/jqf/bin/jqf-zest -c .:$(/path/to/jqf/scripts/examples_classpath.sh) edu.berkeley.cs.jqf.examples.jdk.DateFormatterTest fuzzSimple` .
3.I have tried this but it didn't work:   `java -cp .:$(/path/to/jqf/scripts/examples_classpath.sh) -jar /path/to/jqf/fuzz/target/jqf-fuzz-1.4-SNAPSHOT-zest-cli.jar edu.berkeley.cs.jqf.examples.jdk edu.berkeley.cs.jqf.examples.jdk.DateFormatterTest fuzzSimple `
