### ISSUE TITLE
how to write seed.

### ISSUE THREAD

**Issue by snakefor100** [rohanpadhye/jqf#71]
hello, i have another question. my project code like this:

public void test(String str){
     if(str.startWith("a")){
           System.out.println("success branch").
           if(str.startWith("ab")){
               //success branch 1
            }else{
              //success branch 2
            }
     }
}

the jqf test case code like this:

public void testCase(@Form(xxxGenerator)String name){
test(name);
}

the "xxxGenerator" like AsciiStringGenerator, it difficult to generate name that begin with "a".

so i want to write some success branch params, like "apple,available" to seedfile. but i don't know how to write seedfile. It looks like the seedfile's content is input. not the "apple,available". how to convert the "apple,available" to input ?

![image](https://user-images.githubusercontent.com/8774548/68009345-b3141600-fcbc-11e9-9d26-71657b3aaf90.png)

**Comment by rohanpadhye** [comment]
There is no easy way to reverse an arbitrary generator, since generators are arbitrary functions. You can, however, re-use inputs that correspond to previously generated arguments. See #69.
