### ISSUE TITLE
(solution inside) mktemp: Invalid argument when running bin/jqf-afl-fuzz inside docker image openjdk:8-alpine

### ISSUE THREAD

**Issue by reijin90** [rohanpadhye/JQF#76]
I'm receiving an error when running the example fuzzer:
```
/ # /jqf/bin/jqf-afl-fuzz -i $AFL_DIR/testcases/images/png/ PngTest testRead
Performing pilot run....mktemp: Invalid argument
/jqf/bin/jqf-afl-fuzz: line 170: $tmp_out: ambiguous redirect
  ERROR: Pilot run failed!!!
```
This is due to line 169:
`tmp_out=$(mktemp $JQF_TMP_DIR/jqf-pilot.XXX)`

According to the `mktemp` help the template is supposed to end with `XXXXXX` instead of `XXX`. I'm not sure if this is an alpine only thing, but the issue is fixed once the missing `X`s are added to the line.

**Comment by rohanpadhye** [comment]
That's strange. What OS are you using? On both [MacOS](https://www.freebsd.org/cgi/man.cgi?query=mktemp&sektion=1) and [Linux](https://linux.die.net/man/1/mktemp), the `mktemp` utility allows for three or more X's. The number of X's simply determines the length of the *unique* portion of the temp file name. Since we don't expect more than `62^3` fuzzers running on one system simultaneously, three X's are fine for JQF.

**Comment by reijin90** [comment]
> That's strange. What OS are you using? On both [MacOS](https://www.freebsd.org/cgi/man.cgi?query=mktemp&sektion=1) and [Linux](https://linux.die.net/man/1/mktemp), the `mktemp` utility allows for three or more X's. The number of X's simply determines the length of the _unique_ portion of the temp file name. Since we don't expect more than `62^3` fuzzers running on one system simultaneously, three X's are fine for JQF.

It actually says in the title: Alpine is the distro. I understand the rationale and I definitely agree, it's a weird quirk of Alpine. Not sure if changing this breaks the code for the other distributions, but I've created a workaround, where I make a `sed` call and replace `.XXX` with `.XXXXXX` in all of the `jqf-afl-*` files.

**Comment by rohanpadhye** [comment]
Ahh sorry, I wasn't familiar with the Alpine Linux distro (I thought the
title referred to a specific distribution of OpenJDK!).

That is quite weird that a Linux distro would choose to break compatibility
with such a standard tool. I think six X's might work fine on all the other
systems as well, so let me see if I can make this a permanent fix.
