### ISSUE TITLE
Fuzzing throws an exception "EOF reached" for some custom generators

### ISSUE THREAD

**Issue by peteroupc** [rohanpadhye/jqf#83]
If a fuzz test uses a custom Generator, the fuzz testing can throw an exception like the following depending on how the generator is implemented.

    java.lang.IllegalStateException: java.io.EOFException: EOF reached; total bytes read = 10239, last read got -1 of 4 bytes

I found that the Generator will tend to cause problems if it generates a random size, then generates a number of items based on that size.  The following pattern is an example:

      int len=r.nextInt(1000);
      for(int i=0;i<len;i++){
         byteStream.Write(r.nextInt(128));
      }

On the other hand, if the Generator generates objects of a fixed size, the exception above is not thrown.

A workaround for this is to use the following pattern:

    @Override
    public byte[] generate(SourceOfRandomness random, GenerationStatus __ignore__) {
       Random rnd = new Random(random.nextInt());
       // From now on, use 'rnd' rather than 'random' to generate random numbers
    }

But based on how JQF works, this may not be ideal.

This may be related to issue #1.

**Comment by peteroupc** [comment]
Withdrawn.

**Comment by Justin-Xiang** [comment]
Hi. I came across the same problem, how do you fix it?

**Comment by rohanpadhye** [comment]
@Justin-Xiang This is quite an old issue so the solutions may not still be relevant. Please open a new issue with a minimal example to reproduce the issue. Also check the discussion in #194 in case it is relevant.
