### ISSUE TITLE
JQF + AFL Pilot Error

### ISSUE THREAD

**Issue by alberto64** [rohanpadhye/JQF#85]
Hi everyone, 

Ive been trying to overcome this issue for quite a while. I have a project with test classes with fuzz cases in them. I do as the guide says and compile the java test class that Ill fuzz:

`javac -cp .:$(jqf/scripts/classpath.sh):otherDependencies exampleproject/tester/ProperyTest/JQFFuzzTester .java`

Then I attempt to run the fuzz command: 

`jqf/bin/jqf-afl-fuzz -v -c exampleproject/tester/ProperyTest/ JQFFuzzTester testProperty`

I get the following response:

```
Performing pilot run....  ERROR: Pilot run failed!!!
Exception in thread "main" java.lang.NoClassDefFoundError: org/jacoco/core/analysis/ICoverageVisitor
	at edu.berkeley.cs.jqf.fuzz.repro.ReproDriver.main(ReproDriver.java:61)
Caused by: java.lang.ClassNotFoundException: org.jacoco.core.analysis.ICoverageVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
```

and I consider that its not me.

Here is my test class:

```
package ProperyTest;

import java.io.InputStream;
import org.junit.runner.RunWith;

import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;

@RunWith(JQF.class)
public class JQFFuzzTester {
	
	@Fuzz
	public void testProperty(InputStream stream) throws Exception {
	     // Test execution with inputstream			

	}
}
```

**Comment by rohanpadhye** [comment]
> Then I attempt to run the fuzz command:
> ````jqf/bin/jqf-afl-fuzz -v -c exampleproject/tester/ProperyTest/ JQFFuzzTester testProperty````

I tried reproducing your example, but there were a couple of problems with your command: (1) the classpath should point to the root of the package hierarchy, so just `-c exampleproject/tester`,  followed by the fully-qualified class name `ProperyTester. JQFFuzzTester`, and (2) the method name appears to be `testBlockManagement` instead of `testProperty`.

Make sure that you have [run `setup.sh` in the JQF root directory](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-AFL#install-jqf) to install the AFL proxy and to package all of JQF's dependencies such as JaCoCo.

**Comment by alberto64** [comment]
I went ahead and reruned setup.sh I assumed that jqf-examples is not necessary so I ignored the error, is it needed?
```
[ERROR] Failed to execute goal on project jqf-examples: Could not resolve dependencies for project edu.berkeley.cs.jqf:jqf-examples:jar:1.5-SNAPSHOT: Could not find artifact org.lichess:scalachess_2.12:jar:8.6.8 in archiva.default (https://repo1.maven.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jqf-examples

```
In regards to your comments: 
(1) I fixed the classpath and added the package name into the class name as you suggested, but unfortunately I keep getting the same error.
```
Performing pilot run....  ERROR: Pilot run failed!!!
Exception in thread "main" java.lang.NoClassDefFoundError: org/jacoco/core/analysis/ICoverageVisitor
	at edu.berkeley.cs.jqf.fuzz.repro.ReproDriver.main(ReproDriver.java:61)
Caused by: java.lang.ClassNotFoundException: org.jacoco.core.analysis.ICoverageVisitor
```
(2) The difference in the method names was my bad when typing the example on this comment, my apologies.

**Comment by rohanpadhye** [comment]
I was able to reproduce your error by running `jqf-afl-fuzz` without letting `mvn package` (which is the one of the commands run by `setup.sh`) complete first. Since the packaging is incomplete, the dependency JARs (e.g. JaCoCo) are not present in your directory; hence the error.

I can think of one of two fixes:
1. If you don't want jqf-examples, you can run `mvn -pl '!examples' package` in the JQF root directory. This should build all the JARs except the examples. Quoting/escaping the exclamation symbol may vary depending on your shell. 
2. If you want the full build to succeed, including the examples, make sure that you haven't customized mirrors in `~/.m2/settings.xml` with a wildcard `*` (as this prevents JQF from specifying its own Maven repositories for some examples, such as the scalachess example). See #29 for details on this.

**Comment by alberto64** [comment]
I tried both fixes, I stuck with the second one because the jqf-exampled compiled successfully, but unfortunately it didn't work.

I also tried compiling my test class with the JaCoco package in it to see if it was my code and it also failed.

I wanted to eliminate the possibility that it was my code so I decided to try out the example in the AFL tutorial (PngTest.java) and once again the same result.

```
javac -cp .:$(jqf/scripts/classpath.sh) PngTest.java

jqf/bin/jqf-afl-fuzz -i $AFL_DIR/testcases/images/png/ PngTest testRead

Performing pilot run....  ERROR: Pilot run failed!!!
Exception in thread "main" java.lang.NoClassDefFoundError: org/jacoco/core/analysis/ICoverageVisitor
	at edu.berkeley.cs.jqf.fuzz.repro.ReproDriver.main(ReproDriver.java:61)
Caused by: java.lang.ClassNotFoundException: org.jacoco.core.analysis.ICoverageVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 1 more

```

**Comment by rohanpadhye** [comment]
If everything packaged successfully (that is; if the command `mvn package` or `setup.sh` finished successfully), then you should have the JaCoCo JARs in your local dependencies. You can verify that by running:
```
jar tf JQF_DIR/fuzz/target/dependency/org.jacoco.core-*.jar  | grep ICoverageVisitor
```

(replace `JQF_DIR` with the path to the local JQF repository). Ideally, the result should be:
```
org/jacoco/core/analysis/ICoverageVisitor.class
```

indicating that you do indeed have this class in your dependencies. I can't imagine a scenario where the setup/package completes successfully but the JAR is not built.

**Comment by alberto64** [comment]
It does show up, quick question, the command `javac -cp .:$(jqf/scripts/classpath.sh) PngTest.java` is supposed to add all the dependencies that jqf needs for the analysis, am I right?

**Comment by rohanpadhye** [comment]
Right. Assuming you are running a linux-based OS, where `.` is the classpath separateor. 

You can actually run the script `jqf/scripts/classpath.sh` to see what it expands to. Ideally, `JQF/fuzz/target/dependency/org.jacoco.core-0.8.2.jar` should be present.

PS: I just realized, there may be an issue with spaces in directory names. If the path to your JQF directory has spaces, the classpath script may not expand correctly. Please try in a path without spaces if that is the case and let me know.

**Comment by alberto64** [comment]
Im using Linux 18.04. Im using relative paths to where im executing, I can change everything to Full path, which would be /home/username. Ill get back to you when I try some Ideas that I have.

**Comment by alberto64** [comment]
I tried to isolate the PngTest.class into an empty directory and runned the command: `~/jqf/bin/jqf-afl-fuzz -i $AFL_DIR/testcases/images/png/ PngTest testRead` and got the same result. I was trying to see if for some reason the execution was taking the .java intead of the .class.

The other thing that I tried is adding the Jacoco jar into the -c flag in the jqf command and got different results.

```
~/jqf/bin/jqf-afl-fuzz -c .:~/jacoco/lib/org.jacoco.core-0.8.6.202002280126.jar -i $AFL_DIR/testcases/images/png/ PngTest testRead

Performing pilot run....  ERROR: Pilot run failed!!!
Exception in thread "main" java.lang.NoClassDefFoundError: org/junit/runner/notification/RunListener
	at edu.berkeley.cs.jqf.fuzz.repro.ReproDriver.main(ReproDriver.java:64)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.notification.RunListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 1 more
```

At least I didn't get the error for Jacoco, but now it appears for the JUnit 5 classes.

**Comment by rohanpadhye** [comment]
It really does seem that there is simply a problem with the classpath expansion on your shell. Can you verify if the output of *running* `jqf/scripts/classpath.sh` is indeed a colon-separated list of JAR files, where each JAR file is a valid full path (not including `~`)?

**Comment by alberto64** [comment]
I did as you advised, here are the results:
```
jqf/scripts/classpath.sh
/home/username/jqf/fuzz/target/classes:/home/username/jqf/fuzz/target/test-classes:/home/username/jqf/fuzz/target/dependency/antlr-runtime-3.1.2.jar:/home/username/jqf/fuzz/target/dependency/asm-analysis-6.2.1.jar:/home/username/jqf/fuzz/target/dependency/asm-commons-6.2.1.jar:/home/username/jqf/fuzz/target/dependency/asm-tree-6.2.1.jar:/home/username/jqf/fuzz/target/dependency/generics-resolver-2.0.1.jar:/home/username/jqf/fuzz/target/dependency/hamcrest-core-1.3.jar:/home/username/jqf/fuzz/target/dependency/javaruntype-1.3.jar:/home/username/jqf/fuzz/target/dependency/javassist-3.20.0-GA.jar:/home/username/jqf/fuzz/target/dependency/junit-4.12.jar:/home/username/jqf/fuzz/target/dependency/junit-quickcheck-core-0.8.jar:/home/username/jqf/fuzz/target/dependency/junit-quickcheck-generators-0.8.jar:/home/username/jqf/fuzz/target/dependency/ognl-3.1.12.jar:/home/username/jqf/fuzz/target/dependency/org.jacoco.core-0.8.2.jar:/home/username/jqf/fuzz/target/dependency/org.jacoco.report-0.8.2.jar:/home/username/jqf/fuzz/target/dependency/picocli-4.0.4.jar:/home/username/jqf/fuzz/target/dependency/slf4j-api-1.7.25.jar
```
This gave me the idea of adding the script into the classpath of the JQF command, it got passed the Pilot, but it still didnt run.

```
jqf/bin/jqf-afl-fuzz -c .:$(jqf/scripts/classpath.sh) -i $AFL_DIR/testcases/images/png/ PngTest testRead
Performing pilot run....  Pilot run success! Launching AFL now...
afl-fuzz 2.56b by <lcamtuf@google.com>
[+] You have 1 CPU core and 1 runnable tasks (utilization: 100%).
[*] Checking core_pattern...

[-] Hmm, your system is configured to send core dump notifications to an
    external utility. This will cause issues: there will be an extended delay
    between stumbling upon a crash and having this information relayed to the
    fuzzer via the standard waitpid() API.

    To avoid having crashes misinterpreted as timeouts, please log in as root
    and temporarily modify /proc/sys/kernel/core_pattern, like so:

    echo core >/proc/sys/kernel/core_pattern
[*] Setting up output directories...
[*] Scanning '/home/alberto/Documents/Hackathon/afl/testcases/images/png/'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:not_kitty.png'...
[*] Spinning up the fork server...

[-] PROGRAM ABORT : Timeout while initializing fork server (adjusting -t may help)
         Location : init_forkserver(), afl-fuzz.c:2141
```

This is of course with the PngTest, when I run the command with the class I want to fuzz test the pilot fails because of the depencies my program needs.

**Comment by rohanpadhye** [comment]
As you can see, `/home/username/jqf/fuzz/target/dependency/org.jacoco.core-0.8.2.jar` is in the expansion of JQF's classpath script, so ideally you should not have been getting the original `ClassNotFoundException`  for JaCoCo classes. I'm guessing there may be some other shell or environment configuration that is messing with your classpaths. Have you tried running the AFL tutorial on a different machine or logged in as a different user? It seems to work for most people out-of-the-box.

**Comment by rohanpadhye** [comment]
If all else fails, you can also just avoid using the command-line interface altogether and just use the [JQF Maven Plugin](https://github.com/rohanpadhye/jqf/wiki/JQF-Maven-Plugin). This does run Zest instead of AFL as the fuzzing engine, though.

**Comment by alberto64** [comment]
I tried it out in a clean new enviorment. It worked. It seems that I have configurations that conflicted.

**Comment by xxwxxwen** [comment]
When I run on a new machine with new environment, it still failed.I don't know what is the problem.Could you share what configurations conflicted ? Could you share your test example or how to run it ? Thank you very much!
