### ISSUE TITLE
Enhanced support for gradle projects that use JQF

### ISSUE THREAD

**Issue by dsaff** [rohanpadhye/JQF#86]
I'd like to build some more support for apps that build with gradle and want to fuzz with JQF.  This is not the same as https://github.com/rohanpadhye/JQF/pull/81, which shifted JQF itself to build with gradle.  In this case, it would probably mean building a gradle plugin that would handle the rather tricky classpath details required to get a complicated program (especially written for Android) properly fuzzing.  I got this working a few weeks ago, and it was complex enough that I think many casually-interested devs would get scared off.

I will probably start this in my own repo, but wanted to leave a note here in case you see this being of use in the base repo.  Thanks!

**Comment by rohanpadhye** [comment]
Awesome, this will be a great contribution! Thank you very much :-)

**Comment by dsaff** [comment]
FYI, I ended up taking a different direction on this, so if someone else wants to pick up the thread, feel welcome!

**Comment by rohanpadhye** [comment]
Sorry to hear that, but thanks for coming back to let us know!
