### ISSUE TITLE
How to view test cases in corpus / id_000000

### ISSUE THREAD

**Issue by abc123000111** [rohanpadhye/JQF#88]
Hey, there!
I'm new to Zest and JQF. When the file corpus / id_000000 is opened, garbled characters are displayed. How to convert into a list of test cases? In another word, how to read these corpus in the new program? Thanks!
![QQ20200404-0](https://user-images.githubusercontent.com/34190313/78422220-57492100-7690-11ea-8c6e-fc6f23c37695.png)

**Comment by rohanpadhye** [comment]
Hello! Thanks for trying Zest and JQF. The saved files in the corpus are simply the parameters to the generator(s) for your test method. They will not be human readable. 

You can "repro" your tests by running `mvn jqf:repro`. See [the documentation here](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#reproducing-tests). A repro is essentially a re-run of your test with one or more saved "input" files like the ones from the corpus or failures directory.

If you want to print the fuzzed arguments to your test method before the test itself is run, you can give the argument [`-DprintArgs`](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#other-configurations) when running the repro command. This will cause JQF to print the `toString()` representation of each of the generated arguments to your test method.

If your arguments do not have a nice `toString()` representation, then you can simply modify your test method to insert print statements of your choice when the test method is re-run with the saved inputs. See this example from the Ant test driver, which serializes the XML DOM produced by the generator into a human-readable string: https://github.com/rohanpadhye/JQF/blob/master/examples/src/test/java/edu/berkeley/cs/jqf/examples/ant/ProjectBuilderTest.java#L94

**Comment by abc123000111** [comment]
Thank you so much! So there is no easy way to convert corpus files to files of test cases.

**Comment by rohanpadhye** [comment]
What do you mean by "files of test cases"? The contents of the saved files
depends on the number and types of the arguments to your fuzzed test
method. So, a standalone conversion is not possible because this
information isn't encoded in the files themselves.

If you want AFL-like test cases, then make your test method take in exactly
one parameter of type InputStream. If this is the case, then the contents
of the saved files exactly match the generated input byte by byte.

**Comment by rohanpadhye** [comment]
There is also an [`ArbitraryLengthStringGenerator`](https://github.com/rohanpadhye/JQF/blob/008432b79aeda0b68dd709931e19c988faf21ed0/examples/src/main/java/edu/berkeley/cs/jqf/examples/common/ArbitraryLengthStringGenerator.java) in the `jqf-examples` module, which generates Java `String` objects backed by an InputStream. If you use this generator to fuzz test methods that take in exactly one `String` parameter, then the saved files will have contents that exactly match the contents of the generated strings. 

Here is example usage:
https://github.com/rohanpadhye/JQF/blob/f0979677984bf61e505104fcbda27b442cc561a1/examples/src/test/java/edu/berkeley/cs/jqf/examples/jdk/RegexTest.java#L70-L73
