### ISSUE TITLE
How to debug jqf

### ISSUE THREAD

**Issue by rubby33** [rohanpadhye/JQF#89]
hi,guys,

how can i debug jqf step by step?
Then i can know the details much easier.
I think this is very useful for us .
@rohanpadhye  
any idea?
thanks sincerely.

**Comment by rubby33** [comment]
i can debug jqf step by step now.

**Comment by rohanpadhye** [comment]
Thanks for the update!

**Comment by kldr7** [comment]
> i can debug jqf step by step now.
Can you tell me how you did it，thank you.
