### ISSUE TITLE
assertj assumptions make Zest blind

### ISSUE THREAD

**Issue by monga** [rohanpadhye/JQF#96]
I was experimenting with the [tutorial](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-Zest) and I found that apparently AssertJ assumptions are not effective for guiding the Zest algorithm.

```java
public class CalendarTest {

  @Fuzz
  public void testLeapYearWithAssertJ(@From(CalendarGenerator.class) GregorianCalendar cal) {
    // Assume that the date is Feb 29
    assumeThat(cal.get(MONTH)).isEqualTo(FEBRUARY);
    assumeThat(cal.get(DAY_OF_MONTH)).isEqualTo(29);

    // Under this assumption, validate leap year rules
    assertThat(CalendarLogic.isLeapYear(cal)).as(cal.get(YEAR) + " should be a leap year").isTrue();
  }

  @Fuzz
  public void testLeapYearWithJunitAssertions(@From(CalendarGenerator.class) GregorianCalendar cal) {
    // Assume that the date is Feb 29
    assumeTrue(cal.get(MONTH) == FEBRUARY);
    assumeTrue(cal.get(DAY_OF_MONTH) == 29);

    // Under this assumption, validate leap year rules
    assertTrue(cal.get(YEAR) + " should be a leap year", CalendarLogic.isLeapYear(cal));
  }

  @Fuzz
  public void testLeapYearWithMixAJAssert(@From(CalendarGenerator.class) GregorianCalendar cal) {
    // Assume that the date is Feb 29
    assumeTrue(cal.get(MONTH) == FEBRUARY);
    assumeTrue(cal.get(DAY_OF_MONTH) == 29);

    // Under this assumption, validate leap year rules
    assertThat(CalendarLogic.isLeapYear(cal)).as(cal.get(YEAR) + " should be a leap year").isTrue();
  }

  @Fuzz
  public void testLeapYearWithMixAJAssume(@From(CalendarGenerator.class) GregorianCalendar cal) {
    // Assume that the date is Feb 29
    assumeThat(cal.get(MONTH)).isEqualTo(FEBRUARY);
    assumeThat(cal.get(DAY_OF_MONTH)).isEqualTo(29);

    // Under this assumption, validate leap year rules
    assertTrue(cal.get(YEAR) + " should be a leap year", CalendarLogic.isLeapYear(cal));
  }
}
```
(no changes in the other example code files)

With tests which use AssertJ assumptions (`testLeapYearWithAssertJ` and `testLeapYearWithMixAJAssume`) the rate of valid inputs is approximately 0% (as it is with `-Dblind=true`), while when Junit assumptions are used (`testLeapYearWithJunitAssertions`, `testLeapYearWithMixAJAssert`) the rate raises to 8-15%. Assertions do not affect the result: in fact, my best performance was with Junit assumptions and AssertJ assertions...

**Comment by rohanpadhye** [comment]
Thanks for trying JQF and Zest!

The notion of "validity" used in JQF is the following: if a test execution throws a JUnit [`AssumptionViolatedException`](https://junit.org/junit4/javadoc/4.12/org/junit/AssumptionViolatedException.html), the the input was invalid. If the test execution does not throw any exception or if an exception listed in the the `throws` clause of the test method is thrown, then this is considered a successful test case. If an unexpected exception is thrown (e.g. assertion failures or other run-time exceptions), then the test case is considered a failure. See the [pseudocode of the fuzzing loop in this article](https://github.com/rohanpadhye/JQF/wiki/The-Guidance-interface) for details of how a result is marked as SUCCESS/FAILURE/INVALID.

Now, I have never used AssertJ so I am not sure how it differentiates between assumptions and assertions. But from a quick scan of the docs it looks like the [`assumeThat`](https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/Assumptions.html#assumeThat-boolean-) method simply returns an [`AbstractBooleanAssert`](https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractBooleanAssert.html). If this [fails](https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractBooleanAssert.html#isEqualTo-boolean-), then a [`java.lang.AssertionError`](https://docs.oracle.com/javase/8/docs/api/java/lang/AssertionError.html?is-external=true) is thrown. Therefore, AssertJ does not appear to distinguish between assumption failures and assertion failures. If this true, it means that you would not be able to use AssertJ assumptions to prune invalid inputs in JQF. Please correct me if I am mistaken.

**Comment by monga** [comment]
Thank you for your answer. I decided to show Zest in a course about verification and validation, as a good example of "cutting edge" research which nevertheless produces readily usable tools: it has some rough sides (the strong dependencies on "moving targets" like junit-quickcheck and junit4 are the main issues for me; I also do not like maven, but that's my problem I suppose), but overall it seems to me very solid work, thank you!

On AssertJ, I guess you are right. As is, it seems more a problem of AssertJ than yours: I believe the distinction between the two failures is indeed semantically relevant. It might be related to the independence of AssertJ from JUnit (see https://github.com/joel-costigliola/assertj-core/issues/975). But even JUnit5 might have changed idea about this during its history: see the comment at the bottom of [2.5 of Junit5 docs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assumptions).

**Comment by rohanpadhye** [comment]
Closing for now as there does not seem to be a resolution for this. AssertJ is not compatible with JQF for now due to AssertJ's lack of distinguishing between `assume` and `assert` violations. Feel free to reopen if you have any suggestions or solutions.
