### ISSUE TITLE
How to debug jqf

### ISSUE THREAD

**Issue by kldr7** [rohanpadhye/JQF#97]
Hi,
I wan yo debug jqf step by step,how can I do it, 
I would be very grateful if you could give me an answer
@rohanpadhye

**Comment by rohanpadhye** [comment]
Can you clarify how you are running JQF and what you need to debug? See also #89, which seems to be a suspiciously similar issue. Perhaps @rubby33 has the solution you are looking for.

**Comment by kldr7** [comment]
I use maven
such as:
mvn jqf:fuzz -Dclass=xxxx -Dmethod=xxx
Can I use mvnDebug directly for remote debugging?
In addition, with zest, which file is the entry function in?
Please forgive me for my poor English.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rohan Padhye"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 凌晨1:16
收件人:&nbsp;"rohanpadhye/JQF"<JQF@noreply.github.com&gt;;
抄送:&nbsp;"2451558977"<2451558977@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rohanpadhye/JQF] How to debug jqf (#97)



 
Can you clarify how you are running JQF and what you need to debug? See also #89, which seems to be a suspiciously similar issue. Perhaps @rubby33 has the solution you are looking for.

**Comment by kldr7** [comment]
I've got it

**Comment by rohanpadhye** [comment]
Thanks for the update! If you wish please describe what you did to debug so that future users might also find it useful.
